/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NfsConfig struct for NfsConfig
type NfsConfig struct {
	Exports []NfsExportConfig `json:"exports,omitempty"`
	// The address to which the NFS server is bound. 
	ServiceEndpoint NullableString `json:"serviceEndpoint,omitempty"`
}

// NewNfsConfig instantiates a new NfsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsConfig() *NfsConfig {
	this := NfsConfig{}
	return &this
}

// NewNfsConfigWithDefaults instantiates a new NfsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsConfigWithDefaults() *NfsConfig {
	this := NfsConfig{}
	return &this
}

// GetExports returns the Exports field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NfsConfig) GetExports() []NfsExportConfig {
	if o == nil  {
		var ret []NfsExportConfig
		return ret
	}
	return o.Exports
}

// GetExportsOk returns a tuple with the Exports field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NfsConfig) GetExportsOk() (*[]NfsExportConfig, bool) {
	if o == nil || o.Exports == nil {
		return nil, false
	}
	return &o.Exports, true
}

// HasExports returns a boolean if a field has been set.
func (o *NfsConfig) HasExports() bool {
	if o != nil && o.Exports != nil {
		return true
	}

	return false
}

// SetExports gets a reference to the given []NfsExportConfig and assigns it to the Exports field.
func (o *NfsConfig) SetExports(v []NfsExportConfig) {
	o.Exports = v
}

// GetServiceEndpoint returns the ServiceEndpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NfsConfig) GetServiceEndpoint() string {
	if o == nil || o.ServiceEndpoint.Get() == nil {
		var ret string
		return ret
	}
	return *o.ServiceEndpoint.Get()
}

// GetServiceEndpointOk returns a tuple with the ServiceEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NfsConfig) GetServiceEndpointOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ServiceEndpoint.Get(), o.ServiceEndpoint.IsSet()
}

// HasServiceEndpoint returns a boolean if a field has been set.
func (o *NfsConfig) HasServiceEndpoint() bool {
	if o != nil && o.ServiceEndpoint.IsSet() {
		return true
	}

	return false
}

// SetServiceEndpoint gets a reference to the given NullableString and assigns it to the ServiceEndpoint field.
func (o *NfsConfig) SetServiceEndpoint(v string) {
	o.ServiceEndpoint.Set(&v)
}
// SetServiceEndpointNil sets the value for ServiceEndpoint to be an explicit nil
func (o *NfsConfig) SetServiceEndpointNil() {
	o.ServiceEndpoint.Set(nil)
}

// UnsetServiceEndpoint ensures that no value is present for ServiceEndpoint, not even an explicit nil
func (o *NfsConfig) UnsetServiceEndpoint() {
	o.ServiceEndpoint.Unset()
}

func (o NfsConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Exports != nil {
		toSerialize["exports"] = o.Exports
	}
	if o.ServiceEndpoint.IsSet() {
		toSerialize["serviceEndpoint"] = o.ServiceEndpoint.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableNfsConfig struct {
	value *NfsConfig
	isSet bool
}

func (v NullableNfsConfig) Get() *NfsConfig {
	return v.value
}

func (v *NullableNfsConfig) Set(val *NfsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsConfig(val *NfsConfig) *NullableNfsConfig {
	return &NullableNfsConfig{value: val, isSet: true}
}

func (v NullableNfsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


