/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// UserSessionAllOf struct for UserSessionAllOf
type UserSessionAllOf struct {
	Session UserSessionAllOfSession `json:"session,omitempty"`
}
