/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreatePolicyGroupData struct for CreatePolicyGroupData
type CreatePolicyGroupData struct {
	Name *string `json:"name,omitempty"`
	// A set of authorisation policies to apply to the policy group.
	Specs []PoliciesSpecs `json:"specs,omitempty"`
}

// NewCreatePolicyGroupData instantiates a new CreatePolicyGroupData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePolicyGroupData() *CreatePolicyGroupData {
	this := CreatePolicyGroupData{}
	return &this
}

// NewCreatePolicyGroupDataWithDefaults instantiates a new CreatePolicyGroupData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePolicyGroupDataWithDefaults() *CreatePolicyGroupData {
	this := CreatePolicyGroupData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreatePolicyGroupData) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePolicyGroupData) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreatePolicyGroupData) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreatePolicyGroupData) SetName(v string) {
	o.Name = &v
}

// GetSpecs returns the Specs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePolicyGroupData) GetSpecs() []PoliciesSpecs {
	if o == nil  {
		var ret []PoliciesSpecs
		return ret
	}
	return o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePolicyGroupData) GetSpecsOk() (*[]PoliciesSpecs, bool) {
	if o == nil || o.Specs == nil {
		return nil, false
	}
	return &o.Specs, true
}

// HasSpecs returns a boolean if a field has been set.
func (o *CreatePolicyGroupData) HasSpecs() bool {
	if o != nil && o.Specs != nil {
		return true
	}

	return false
}

// SetSpecs gets a reference to the given []PoliciesSpecs and assigns it to the Specs field.
func (o *CreatePolicyGroupData) SetSpecs(v []PoliciesSpecs) {
	o.Specs = v
}

func (o CreatePolicyGroupData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Specs != nil {
		toSerialize["specs"] = o.Specs
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePolicyGroupData struct {
	value *CreatePolicyGroupData
	isSet bool
}

func (v NullableCreatePolicyGroupData) Get() *CreatePolicyGroupData {
	return v.value
}

func (v *NullableCreatePolicyGroupData) Set(val *CreatePolicyGroupData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePolicyGroupData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePolicyGroupData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePolicyGroupData(val *CreatePolicyGroupData) *NullableCreatePolicyGroupData {
	return &NullableCreatePolicyGroupData{value: val, isSet: true}
}

func (v NullableCreatePolicyGroupData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePolicyGroupData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


