/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SetCordonedNodeData struct for SetCordonedNodeData
type SetCordonedNodeData struct {
	// Marks the node's desired cordoned state state.  A cordoned node will not have new volume deployments scheduled on it. 
	Cordoned *bool `json:"cordoned,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewSetCordonedNodeData instantiates a new SetCordonedNodeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetCordonedNodeData() *SetCordonedNodeData {
	this := SetCordonedNodeData{}
	return &this
}

// NewSetCordonedNodeDataWithDefaults instantiates a new SetCordonedNodeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetCordonedNodeDataWithDefaults() *SetCordonedNodeData {
	this := SetCordonedNodeData{}
	return &this
}

// GetCordoned returns the Cordoned field value if set, zero value otherwise.
func (o *SetCordonedNodeData) GetCordoned() bool {
	if o == nil || o.Cordoned == nil {
		var ret bool
		return ret
	}
	return *o.Cordoned
}

// GetCordonedOk returns a tuple with the Cordoned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCordonedNodeData) GetCordonedOk() (*bool, bool) {
	if o == nil || o.Cordoned == nil {
		return nil, false
	}
	return o.Cordoned, true
}

// HasCordoned returns a boolean if a field has been set.
func (o *SetCordonedNodeData) HasCordoned() bool {
	if o != nil && o.Cordoned != nil {
		return true
	}

	return false
}

// SetCordoned gets a reference to the given bool and assigns it to the Cordoned field.
func (o *SetCordonedNodeData) SetCordoned(v bool) {
	o.Cordoned = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SetCordonedNodeData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCordonedNodeData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SetCordonedNodeData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SetCordonedNodeData) SetVersion(v string) {
	o.Version = &v
}

func (o SetCordonedNodeData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cordoned != nil {
		toSerialize["cordoned"] = o.Cordoned
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableSetCordonedNodeData struct {
	value *SetCordonedNodeData
	isSet bool
}

func (v NullableSetCordonedNodeData) Get() *SetCordonedNodeData {
	return v.value
}

func (v *NullableSetCordonedNodeData) Set(val *SetCordonedNodeData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetCordonedNodeData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetCordonedNodeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetCordonedNodeData(val *SetCordonedNodeData) *NullableSetCordonedNodeData {
	return &NullableSetCordonedNodeData{value: val, isSet: true}
}

func (v NullableSetCordonedNodeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetCordonedNodeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


