/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NFSVolumeExports struct for NFSVolumeExports
type NFSVolumeExports struct {
	Exports *[]NfsExportConfig `json:"exports,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewNFSVolumeExports instantiates a new NFSVolumeExports object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNFSVolumeExports() *NFSVolumeExports {
	this := NFSVolumeExports{}
	return &this
}

// NewNFSVolumeExportsWithDefaults instantiates a new NFSVolumeExports object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNFSVolumeExportsWithDefaults() *NFSVolumeExports {
	this := NFSVolumeExports{}
	return &this
}

// GetExports returns the Exports field value if set, zero value otherwise.
func (o *NFSVolumeExports) GetExports() []NfsExportConfig {
	if o == nil || o.Exports == nil {
		var ret []NfsExportConfig
		return ret
	}
	return *o.Exports
}

// GetExportsOk returns a tuple with the Exports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NFSVolumeExports) GetExportsOk() (*[]NfsExportConfig, bool) {
	if o == nil || o.Exports == nil {
		return nil, false
	}
	return o.Exports, true
}

// HasExports returns a boolean if a field has been set.
func (o *NFSVolumeExports) HasExports() bool {
	if o != nil && o.Exports != nil {
		return true
	}

	return false
}

// SetExports gets a reference to the given []NfsExportConfig and assigns it to the Exports field.
func (o *NFSVolumeExports) SetExports(v []NfsExportConfig) {
	o.Exports = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *NFSVolumeExports) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NFSVolumeExports) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *NFSVolumeExports) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *NFSVolumeExports) SetVersion(v string) {
	o.Version = &v
}

func (o NFSVolumeExports) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Exports != nil {
		toSerialize["exports"] = o.Exports
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableNFSVolumeExports struct {
	value *NFSVolumeExports
	isSet bool
}

func (v NullableNFSVolumeExports) Get() *NFSVolumeExports {
	return v.value
}

func (v *NullableNFSVolumeExports) Set(val *NFSVolumeExports) {
	v.value = val
	v.isSet = true
}

func (v NullableNFSVolumeExports) IsSet() bool {
	return v.isSet
}

func (v *NullableNFSVolumeExports) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNFSVolumeExports(val *NFSVolumeExports) *NullableNFSVolumeExports {
	return &NullableNFSVolumeExports{value: val, isSet: true}
}

func (v NullableNFSVolumeExports) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNFSVolumeExports) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


