/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// NodeHealth The operational health of a node entity 
type NodeHealth string

// List of NodeHealth
const (
	NODEHEALTH_ONLINE NodeHealth = "online"
	NODEHEALTH_OFFLINE NodeHealth = "offline"
	NODEHEALTH_UNKNOWN NodeHealth = "unknown"
)

// All allowed values of NodeHealth enum
var AllowedNodeHealthEnumValues = []NodeHealth{
	"online",
	"offline",
	"unknown",
}

func (v *NodeHealth) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NodeHealth(value)
	for _, existing := range AllowedNodeHealthEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NodeHealth", value)
}

// NewNodeHealthFromValue returns a pointer to a valid NodeHealth
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNodeHealthFromValue(v string) (*NodeHealth, error) {
	ev := NodeHealth(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NodeHealth: valid values are %v", v, AllowedNodeHealthEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NodeHealth) IsValid() bool {
	for _, existing := range AllowedNodeHealthEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NodeHealth value
func (v NodeHealth) Ptr() *NodeHealth {
	return &v
}

type NullableNodeHealth struct {
	value *NodeHealth
	isSet bool
}

func (v NullableNodeHealth) Get() *NodeHealth {
	return v.value
}

func (v *NullableNodeHealth) Set(val *NodeHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeHealth(val *NodeHealth) *NullableNodeHealth {
	return &NullableNodeHealth{value: val, isSet: true}
}

func (v NullableNodeHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

