/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// MasterDeploymentInfoAllOf struct for MasterDeploymentInfoAllOf
type MasterDeploymentInfoAllOf struct {
	Health MasterHealth `json:"health,omitempty"`
}
