/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NfsAcl struct for NfsAcl
type NfsAcl struct {
	Identity *NfsAclIdentity `json:"identity,omitempty"`
	SquashConfig *NfsAclSquashConfig `json:"squashConfig,omitempty"`
	// The access level this ACL grants - read-only, or read-write. 
	AccessLevel *string `json:"accessLevel,omitempty"`
}

// NewNfsAcl instantiates a new NfsAcl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsAcl() *NfsAcl {
	this := NfsAcl{}
	return &this
}

// NewNfsAclWithDefaults instantiates a new NfsAcl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsAclWithDefaults() *NfsAcl {
	this := NfsAcl{}
	return &this
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *NfsAcl) GetIdentity() NfsAclIdentity {
	if o == nil || o.Identity == nil {
		var ret NfsAclIdentity
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAcl) GetIdentityOk() (*NfsAclIdentity, bool) {
	if o == nil || o.Identity == nil {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *NfsAcl) HasIdentity() bool {
	if o != nil && o.Identity != nil {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given NfsAclIdentity and assigns it to the Identity field.
func (o *NfsAcl) SetIdentity(v NfsAclIdentity) {
	o.Identity = &v
}

// GetSquashConfig returns the SquashConfig field value if set, zero value otherwise.
func (o *NfsAcl) GetSquashConfig() NfsAclSquashConfig {
	if o == nil || o.SquashConfig == nil {
		var ret NfsAclSquashConfig
		return ret
	}
	return *o.SquashConfig
}

// GetSquashConfigOk returns a tuple with the SquashConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAcl) GetSquashConfigOk() (*NfsAclSquashConfig, bool) {
	if o == nil || o.SquashConfig == nil {
		return nil, false
	}
	return o.SquashConfig, true
}

// HasSquashConfig returns a boolean if a field has been set.
func (o *NfsAcl) HasSquashConfig() bool {
	if o != nil && o.SquashConfig != nil {
		return true
	}

	return false
}

// SetSquashConfig gets a reference to the given NfsAclSquashConfig and assigns it to the SquashConfig field.
func (o *NfsAcl) SetSquashConfig(v NfsAclSquashConfig) {
	o.SquashConfig = &v
}

// GetAccessLevel returns the AccessLevel field value if set, zero value otherwise.
func (o *NfsAcl) GetAccessLevel() string {
	if o == nil || o.AccessLevel == nil {
		var ret string
		return ret
	}
	return *o.AccessLevel
}

// GetAccessLevelOk returns a tuple with the AccessLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAcl) GetAccessLevelOk() (*string, bool) {
	if o == nil || o.AccessLevel == nil {
		return nil, false
	}
	return o.AccessLevel, true
}

// HasAccessLevel returns a boolean if a field has been set.
func (o *NfsAcl) HasAccessLevel() bool {
	if o != nil && o.AccessLevel != nil {
		return true
	}

	return false
}

// SetAccessLevel gets a reference to the given string and assigns it to the AccessLevel field.
func (o *NfsAcl) SetAccessLevel(v string) {
	o.AccessLevel = &v
}

func (o NfsAcl) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Identity != nil {
		toSerialize["identity"] = o.Identity
	}
	if o.SquashConfig != nil {
		toSerialize["squashConfig"] = o.SquashConfig
	}
	if o.AccessLevel != nil {
		toSerialize["accessLevel"] = o.AccessLevel
	}
	return json.Marshal(toSerialize)
}

type NullableNfsAcl struct {
	value *NfsAcl
	isSet bool
}

func (v NullableNfsAcl) Get() *NfsAcl {
	return v.value
}

func (v *NullableNfsAcl) Set(val *NfsAcl) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsAcl) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsAcl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsAcl(val *NfsAcl) *NullableNfsAcl {
	return &NullableNfsAcl{value: val, isSet: true}
}

func (v NullableNfsAcl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsAcl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


