/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NfsAclIdentity struct for NfsAclIdentity
type NfsAclIdentity struct {
	// The identity type used to identify the nfs client. 
	IdentityType *string `json:"identityType,omitempty"`
	// NFS identity matcher. For \"cidr\", this should be a valid CIDR block string such as \"10.0.0.0/8\". For \"hostname\", this must be the hostname sent by the client, with ? and * wildcard characters. For netgroup, this must be in the form of \"@netgroup\" with ? and * wildcard characters. 
	Matcher *string `json:"matcher,omitempty"`
}

// NewNfsAclIdentity instantiates a new NfsAclIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsAclIdentity() *NfsAclIdentity {
	this := NfsAclIdentity{}
	return &this
}

// NewNfsAclIdentityWithDefaults instantiates a new NfsAclIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsAclIdentityWithDefaults() *NfsAclIdentity {
	this := NfsAclIdentity{}
	return &this
}

// GetIdentityType returns the IdentityType field value if set, zero value otherwise.
func (o *NfsAclIdentity) GetIdentityType() string {
	if o == nil || o.IdentityType == nil {
		var ret string
		return ret
	}
	return *o.IdentityType
}

// GetIdentityTypeOk returns a tuple with the IdentityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAclIdentity) GetIdentityTypeOk() (*string, bool) {
	if o == nil || o.IdentityType == nil {
		return nil, false
	}
	return o.IdentityType, true
}

// HasIdentityType returns a boolean if a field has been set.
func (o *NfsAclIdentity) HasIdentityType() bool {
	if o != nil && o.IdentityType != nil {
		return true
	}

	return false
}

// SetIdentityType gets a reference to the given string and assigns it to the IdentityType field.
func (o *NfsAclIdentity) SetIdentityType(v string) {
	o.IdentityType = &v
}

// GetMatcher returns the Matcher field value if set, zero value otherwise.
func (o *NfsAclIdentity) GetMatcher() string {
	if o == nil || o.Matcher == nil {
		var ret string
		return ret
	}
	return *o.Matcher
}

// GetMatcherOk returns a tuple with the Matcher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAclIdentity) GetMatcherOk() (*string, bool) {
	if o == nil || o.Matcher == nil {
		return nil, false
	}
	return o.Matcher, true
}

// HasMatcher returns a boolean if a field has been set.
func (o *NfsAclIdentity) HasMatcher() bool {
	if o != nil && o.Matcher != nil {
		return true
	}

	return false
}

// SetMatcher gets a reference to the given string and assigns it to the Matcher field.
func (o *NfsAclIdentity) SetMatcher(v string) {
	o.Matcher = &v
}

func (o NfsAclIdentity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdentityType != nil {
		toSerialize["identityType"] = o.IdentityType
	}
	if o.Matcher != nil {
		toSerialize["matcher"] = o.Matcher
	}
	return json.Marshal(toSerialize)
}

type NullableNfsAclIdentity struct {
	value *NfsAclIdentity
	isSet bool
}

func (v NullableNfsAclIdentity) Get() *NfsAclIdentity {
	return v.value
}

func (v *NullableNfsAclIdentity) Set(val *NfsAclIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsAclIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsAclIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsAclIdentity(val *NfsAclIdentity) *NullableNfsAclIdentity {
	return &NullableNfsAclIdentity{value: val, isSet: true}
}

func (v NullableNfsAclIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsAclIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


