/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// MasterHealth The operational health of a volume master deployment 
type MasterHealth string

// List of MasterHealth
const (
	MASTERHEALTH_ONLINE MasterHealth = "online"
	MASTERHEALTH_OFFLINE MasterHealth = "offline"
	MASTERHEALTH_UNKNOWN MasterHealth = "unknown"
)

// All allowed values of MasterHealth enum
var AllowedMasterHealthEnumValues = []MasterHealth{
	"online",
	"offline",
	"unknown",
}

func (v *MasterHealth) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MasterHealth(value)
	for _, existing := range AllowedMasterHealthEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MasterHealth", value)
}

// NewMasterHealthFromValue returns a pointer to a valid MasterHealth
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMasterHealthFromValue(v string) (*MasterHealth, error) {
	ev := MasterHealth(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MasterHealth: valid values are %v", v, AllowedMasterHealthEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MasterHealth) IsValid() bool {
	for _, existing := range AllowedMasterHealthEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MasterHealth value
func (v MasterHealth) Ptr() *MasterHealth {
	return &v
}

type NullableMasterHealth struct {
	value *MasterHealth
	isSet bool
}

func (v NullableMasterHealth) Get() *MasterHealth {
	return v.value
}

func (v *NullableMasterHealth) Set(val *MasterHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableMasterHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableMasterHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMasterHealth(val *MasterHealth) *NullableMasterHealth {
	return &NullableMasterHealth{value: val, isSet: true}
}

func (v NullableMasterHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMasterHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

