/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NfsExportConfig struct for NfsExportConfig
type NfsExportConfig struct {
	// ID for this export 
	ExportID *uint64 `json:"exportID,omitempty"`
	// The path relative to the volume root to serve as the export root 
	Path *string `json:"path,omitempty"`
	// The configured pseudo path in the NFS virtual filesystem. This is the path clients will see when traversing to this export on the NFS share. 
	PseudoPath *string `json:"pseudoPath,omitempty"`
	Acls *[]NfsAcl `json:"acls,omitempty"`
}

// NewNfsExportConfig instantiates a new NfsExportConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsExportConfig() *NfsExportConfig {
	this := NfsExportConfig{}
	var path string = ""
	this.Path = &path
	var pseudoPath string = ""
	this.PseudoPath = &pseudoPath
	return &this
}

// NewNfsExportConfigWithDefaults instantiates a new NfsExportConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsExportConfigWithDefaults() *NfsExportConfig {
	this := NfsExportConfig{}
	var path string = ""
	this.Path = &path
	var pseudoPath string = ""
	this.PseudoPath = &pseudoPath
	return &this
}

// GetExportID returns the ExportID field value if set, zero value otherwise.
func (o *NfsExportConfig) GetExportID() uint64 {
	if o == nil || o.ExportID == nil {
		var ret uint64
		return ret
	}
	return *o.ExportID
}

// GetExportIDOk returns a tuple with the ExportID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsExportConfig) GetExportIDOk() (*uint64, bool) {
	if o == nil || o.ExportID == nil {
		return nil, false
	}
	return o.ExportID, true
}

// HasExportID returns a boolean if a field has been set.
func (o *NfsExportConfig) HasExportID() bool {
	if o != nil && o.ExportID != nil {
		return true
	}

	return false
}

// SetExportID gets a reference to the given uint64 and assigns it to the ExportID field.
func (o *NfsExportConfig) SetExportID(v uint64) {
	o.ExportID = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *NfsExportConfig) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsExportConfig) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *NfsExportConfig) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *NfsExportConfig) SetPath(v string) {
	o.Path = &v
}

// GetPseudoPath returns the PseudoPath field value if set, zero value otherwise.
func (o *NfsExportConfig) GetPseudoPath() string {
	if o == nil || o.PseudoPath == nil {
		var ret string
		return ret
	}
	return *o.PseudoPath
}

// GetPseudoPathOk returns a tuple with the PseudoPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsExportConfig) GetPseudoPathOk() (*string, bool) {
	if o == nil || o.PseudoPath == nil {
		return nil, false
	}
	return o.PseudoPath, true
}

// HasPseudoPath returns a boolean if a field has been set.
func (o *NfsExportConfig) HasPseudoPath() bool {
	if o != nil && o.PseudoPath != nil {
		return true
	}

	return false
}

// SetPseudoPath gets a reference to the given string and assigns it to the PseudoPath field.
func (o *NfsExportConfig) SetPseudoPath(v string) {
	o.PseudoPath = &v
}

// GetAcls returns the Acls field value if set, zero value otherwise.
func (o *NfsExportConfig) GetAcls() []NfsAcl {
	if o == nil || o.Acls == nil {
		var ret []NfsAcl
		return ret
	}
	return *o.Acls
}

// GetAclsOk returns a tuple with the Acls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsExportConfig) GetAclsOk() (*[]NfsAcl, bool) {
	if o == nil || o.Acls == nil {
		return nil, false
	}
	return o.Acls, true
}

// HasAcls returns a boolean if a field has been set.
func (o *NfsExportConfig) HasAcls() bool {
	if o != nil && o.Acls != nil {
		return true
	}

	return false
}

// SetAcls gets a reference to the given []NfsAcl and assigns it to the Acls field.
func (o *NfsExportConfig) SetAcls(v []NfsAcl) {
	o.Acls = &v
}

func (o NfsExportConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExportID != nil {
		toSerialize["exportID"] = o.ExportID
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.PseudoPath != nil {
		toSerialize["pseudoPath"] = o.PseudoPath
	}
	if o.Acls != nil {
		toSerialize["acls"] = o.Acls
	}
	return json.Marshal(toSerialize)
}

type NullableNfsExportConfig struct {
	value *NfsExportConfig
	isSet bool
}

func (v NullableNfsExportConfig) Get() *NfsExportConfig {
	return v.value
}

func (v *NullableNfsExportConfig) Set(val *NfsExportConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsExportConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsExportConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsExportConfig(val *NfsExportConfig) *NullableNfsExportConfig {
	return &NullableNfsExportConfig{value: val, isSet: true}
}

func (v NullableNfsExportConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsExportConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


