/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// MasterDeploymentInfoAllOf struct for MasterDeploymentInfoAllOf
type MasterDeploymentInfoAllOf struct {
	Health *MasterHealth `json:"health,omitempty"`
}

// NewMasterDeploymentInfoAllOf instantiates a new MasterDeploymentInfoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMasterDeploymentInfoAllOf() *MasterDeploymentInfoAllOf {
	this := MasterDeploymentInfoAllOf{}
	return &this
}

// NewMasterDeploymentInfoAllOfWithDefaults instantiates a new MasterDeploymentInfoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMasterDeploymentInfoAllOfWithDefaults() *MasterDeploymentInfoAllOf {
	this := MasterDeploymentInfoAllOf{}
	return &this
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *MasterDeploymentInfoAllOf) GetHealth() MasterHealth {
	if o == nil || o.Health == nil {
		var ret MasterHealth
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MasterDeploymentInfoAllOf) GetHealthOk() (*MasterHealth, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *MasterDeploymentInfoAllOf) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given MasterHealth and assigns it to the Health field.
func (o *MasterDeploymentInfoAllOf) SetHealth(v MasterHealth) {
	o.Health = &v
}

func (o MasterDeploymentInfoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	return json.Marshal(toSerialize)
}

type NullableMasterDeploymentInfoAllOf struct {
	value *MasterDeploymentInfoAllOf
	isSet bool
}

func (v NullableMasterDeploymentInfoAllOf) Get() *MasterDeploymentInfoAllOf {
	return v.value
}

func (v *NullableMasterDeploymentInfoAllOf) Set(val *MasterDeploymentInfoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMasterDeploymentInfoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMasterDeploymentInfoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMasterDeploymentInfoAllOf(val *MasterDeploymentInfoAllOf) *NullableMasterDeploymentInfoAllOf {
	return &NullableMasterDeploymentInfoAllOf{value: val, isSet: true}
}

func (v NullableMasterDeploymentInfoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMasterDeploymentInfoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


