/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// Strategy The logic to use when placing the volume replicas across the available nodes. Possible options for this field include an availability zone aware rule and recommended rule in which multiple factors like available disk space, recent number of errors on the nodes, etc, are taken into consideration. Defaults to using a recommended placement strategy. 
type Strategy struct {
	Strategy string `json:"strategy,omitempty"`
	Options *StrategyOptions `json:"options,omitempty"`
}
