/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// LogFormat This setting determines the format nodes in the cluster will use for log entries. This setting is only checked by nodes on startup. Changing this setting will not affect the behaviour of nodes that are already operational. 
type LogFormat string

// List of LogFormat
const (
	LOGFORMAT_DEFAULT LogFormat = "default"
	LOGFORMAT_JSON LogFormat = "json"
)

// All allowed values of LogFormat enum
var AllowedLogFormatEnumValues = []LogFormat{
	"default",
	"json",
}

func (v *LogFormat) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LogFormat(value)
	for _, existing := range AllowedLogFormatEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LogFormat", value)
}

// NewLogFormatFromValue returns a pointer to a valid LogFormat
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLogFormatFromValue(v string) (*LogFormat, error) {
	ev := LogFormat(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LogFormat: valid values are %v", v, AllowedLogFormatEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LogFormat) IsValid() bool {
	for _, existing := range AllowedLogFormatEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LogFormat value
func (v LogFormat) Ptr() *LogFormat {
	return &v
}

type NullableLogFormat struct {
	value *LogFormat
	isSet bool
}

func (v NullableLogFormat) Get() *LogFormat {
	return v.value
}

func (v *NullableLogFormat) Set(val *LogFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableLogFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableLogFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogFormat(val *LogFormat) *NullableLogFormat {
	return &NullableLogFormat{value: val, isSet: true}
}

func (v NullableLogFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

