/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UserSessionAllOfSession struct for UserSessionAllOfSession
type UserSessionAllOfSession struct {
	// The maximum duration which the auth session  will remain valid for in seconds. 
	ExpiresInSeconds *uint64 `json:"expiresInSeconds,omitempty"`
	// The JWT token for the auth session. 
	Token *string `json:"token,omitempty"`
}

// NewUserSessionAllOfSession instantiates a new UserSessionAllOfSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionAllOfSession() *UserSessionAllOfSession {
	this := UserSessionAllOfSession{}
	return &this
}

// NewUserSessionAllOfSessionWithDefaults instantiates a new UserSessionAllOfSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionAllOfSessionWithDefaults() *UserSessionAllOfSession {
	this := UserSessionAllOfSession{}
	return &this
}

// GetExpiresInSeconds returns the ExpiresInSeconds field value if set, zero value otherwise.
func (o *UserSessionAllOfSession) GetExpiresInSeconds() uint64 {
	if o == nil || o.ExpiresInSeconds == nil {
		var ret uint64
		return ret
	}
	return *o.ExpiresInSeconds
}

// GetExpiresInSecondsOk returns a tuple with the ExpiresInSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSessionAllOfSession) GetExpiresInSecondsOk() (*uint64, bool) {
	if o == nil || o.ExpiresInSeconds == nil {
		return nil, false
	}
	return o.ExpiresInSeconds, true
}

// HasExpiresInSeconds returns a boolean if a field has been set.
func (o *UserSessionAllOfSession) HasExpiresInSeconds() bool {
	if o != nil && o.ExpiresInSeconds != nil {
		return true
	}

	return false
}

// SetExpiresInSeconds gets a reference to the given uint64 and assigns it to the ExpiresInSeconds field.
func (o *UserSessionAllOfSession) SetExpiresInSeconds(v uint64) {
	o.ExpiresInSeconds = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UserSessionAllOfSession) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSessionAllOfSession) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UserSessionAllOfSession) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UserSessionAllOfSession) SetToken(v string) {
	o.Token = &v
}

func (o UserSessionAllOfSession) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExpiresInSeconds != nil {
		toSerialize["expiresInSeconds"] = o.ExpiresInSeconds
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableUserSessionAllOfSession struct {
	value *UserSessionAllOfSession
	isSet bool
}

func (v NullableUserSessionAllOfSession) Get() *UserSessionAllOfSession {
	return v.value
}

func (v *NullableUserSessionAllOfSession) Set(val *UserSessionAllOfSession) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionAllOfSession) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionAllOfSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionAllOfSession(val *UserSessionAllOfSession) *NullableUserSessionAllOfSession {
	return &NullableUserSessionAllOfSession{value: val, isSet: true}
}

func (v NullableUserSessionAllOfSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionAllOfSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


