/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NfsAclSquashConfig struct for NfsAclSquashConfig
type NfsAclSquashConfig struct {
	Uid *int64 `json:"uid,omitempty"`
	Gid *int64 `json:"gid,omitempty"`
	// SquashConfig defines the root squashing behaviour.  When a client creates a file, it sends the user UID from the client. If the client is running as root, this sends uid=0. Root squashing allows the NFS administrator to prevent the client from writing as \"root\" to the NFS share, instead mapping the client to a new UID/GID (usually nfsnobody, -2). \"none\" performs no UID/GID alterations, using the values sent by the client. \"root\" maps UID & GID 0 to the values specified. \"rootuid\" maps UID 0 and a GID of any value to the value specified. \"all\" maps changes all UID and GID values to those specified. 
	Squash *string `json:"squash,omitempty"`
}

// NewNfsAclSquashConfig instantiates a new NfsAclSquashConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNfsAclSquashConfig() *NfsAclSquashConfig {
	this := NfsAclSquashConfig{}
	return &this
}

// NewNfsAclSquashConfigWithDefaults instantiates a new NfsAclSquashConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNfsAclSquashConfigWithDefaults() *NfsAclSquashConfig {
	this := NfsAclSquashConfig{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *NfsAclSquashConfig) GetUid() int64 {
	if o == nil || o.Uid == nil {
		var ret int64
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAclSquashConfig) GetUidOk() (*int64, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *NfsAclSquashConfig) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given int64 and assigns it to the Uid field.
func (o *NfsAclSquashConfig) SetUid(v int64) {
	o.Uid = &v
}

// GetGid returns the Gid field value if set, zero value otherwise.
func (o *NfsAclSquashConfig) GetGid() int64 {
	if o == nil || o.Gid == nil {
		var ret int64
		return ret
	}
	return *o.Gid
}

// GetGidOk returns a tuple with the Gid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAclSquashConfig) GetGidOk() (*int64, bool) {
	if o == nil || o.Gid == nil {
		return nil, false
	}
	return o.Gid, true
}

// HasGid returns a boolean if a field has been set.
func (o *NfsAclSquashConfig) HasGid() bool {
	if o != nil && o.Gid != nil {
		return true
	}

	return false
}

// SetGid gets a reference to the given int64 and assigns it to the Gid field.
func (o *NfsAclSquashConfig) SetGid(v int64) {
	o.Gid = &v
}

// GetSquash returns the Squash field value if set, zero value otherwise.
func (o *NfsAclSquashConfig) GetSquash() string {
	if o == nil || o.Squash == nil {
		var ret string
		return ret
	}
	return *o.Squash
}

// GetSquashOk returns a tuple with the Squash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NfsAclSquashConfig) GetSquashOk() (*string, bool) {
	if o == nil || o.Squash == nil {
		return nil, false
	}
	return o.Squash, true
}

// HasSquash returns a boolean if a field has been set.
func (o *NfsAclSquashConfig) HasSquash() bool {
	if o != nil && o.Squash != nil {
		return true
	}

	return false
}

// SetSquash gets a reference to the given string and assigns it to the Squash field.
func (o *NfsAclSquashConfig) SetSquash(v string) {
	o.Squash = &v
}

func (o NfsAclSquashConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.Gid != nil {
		toSerialize["gid"] = o.Gid
	}
	if o.Squash != nil {
		toSerialize["squash"] = o.Squash
	}
	return json.Marshal(toSerialize)
}

type NullableNfsAclSquashConfig struct {
	value *NfsAclSquashConfig
	isSet bool
}

func (v NullableNfsAclSquashConfig) Get() *NfsAclSquashConfig {
	return v.value
}

func (v *NullableNfsAclSquashConfig) Set(val *NfsAclSquashConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNfsAclSquashConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNfsAclSquashConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNfsAclSquashConfig(val *NfsAclSquashConfig) *NullableNfsAclSquashConfig {
	return &NullableNfsAclSquashConfig{value: val, isSet: true}
}

func (v NullableNfsAclSquashConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNfsAclSquashConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


