/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// Licence A representation of a cluster's licence properties 
type Licence struct {
	// A unique identifier for a cluster. The format of this type is undefined and may change but the defined properties will not change. 
	ClusterID *string `json:"clusterID,omitempty"`
	// The time after which a licence will no longer be valid This timestamp is set when the licence is created. String format is RFC3339. 
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// The allowed provisioning capacity in bytes This value if for the cluster, if provisioning a volume brings the cluster's total provisioned capacity above it the request will fail 
	ClusterCapacityBytes *uint64 `json:"clusterCapacityBytes,omitempty"`
	// Sum of the size of all volumes in the cluster 
	UsedBytes *uint64 `json:"usedBytes,omitempty"`
	// Denotes which category the licence belongs to 
	Kind *string `json:"kind,omitempty"`
	// A user friendly reference to the customer 
	CustomerName *string `json:"customerName,omitempty"`
	// A list of product features which are enabled by the  licence, subject to the installed version. 
	Features []string `json:"features,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewLicence instantiates a new Licence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicence() *Licence {
	this := Licence{}
	return &this
}

// NewLicenceWithDefaults instantiates a new Licence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenceWithDefaults() *Licence {
	this := Licence{}
	return &this
}

// GetClusterID returns the ClusterID field value if set, zero value otherwise.
func (o *Licence) GetClusterID() string {
	if o == nil || o.ClusterID == nil {
		var ret string
		return ret
	}
	return *o.ClusterID
}

// GetClusterIDOk returns a tuple with the ClusterID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetClusterIDOk() (*string, bool) {
	if o == nil || o.ClusterID == nil {
		return nil, false
	}
	return o.ClusterID, true
}

// HasClusterID returns a boolean if a field has been set.
func (o *Licence) HasClusterID() bool {
	if o != nil && o.ClusterID != nil {
		return true
	}

	return false
}

// SetClusterID gets a reference to the given string and assigns it to the ClusterID field.
func (o *Licence) SetClusterID(v string) {
	o.ClusterID = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Licence) GetExpiresAt() time.Time {
	if o == nil || o.ExpiresAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || o.ExpiresAt == nil {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Licence) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt != nil {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *Licence) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetClusterCapacityBytes returns the ClusterCapacityBytes field value if set, zero value otherwise.
func (o *Licence) GetClusterCapacityBytes() uint64 {
	if o == nil || o.ClusterCapacityBytes == nil {
		var ret uint64
		return ret
	}
	return *o.ClusterCapacityBytes
}

// GetClusterCapacityBytesOk returns a tuple with the ClusterCapacityBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetClusterCapacityBytesOk() (*uint64, bool) {
	if o == nil || o.ClusterCapacityBytes == nil {
		return nil, false
	}
	return o.ClusterCapacityBytes, true
}

// HasClusterCapacityBytes returns a boolean if a field has been set.
func (o *Licence) HasClusterCapacityBytes() bool {
	if o != nil && o.ClusterCapacityBytes != nil {
		return true
	}

	return false
}

// SetClusterCapacityBytes gets a reference to the given uint64 and assigns it to the ClusterCapacityBytes field.
func (o *Licence) SetClusterCapacityBytes(v uint64) {
	o.ClusterCapacityBytes = &v
}

// GetUsedBytes returns the UsedBytes field value if set, zero value otherwise.
func (o *Licence) GetUsedBytes() uint64 {
	if o == nil || o.UsedBytes == nil {
		var ret uint64
		return ret
	}
	return *o.UsedBytes
}

// GetUsedBytesOk returns a tuple with the UsedBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetUsedBytesOk() (*uint64, bool) {
	if o == nil || o.UsedBytes == nil {
		return nil, false
	}
	return o.UsedBytes, true
}

// HasUsedBytes returns a boolean if a field has been set.
func (o *Licence) HasUsedBytes() bool {
	if o != nil && o.UsedBytes != nil {
		return true
	}

	return false
}

// SetUsedBytes gets a reference to the given uint64 and assigns it to the UsedBytes field.
func (o *Licence) SetUsedBytes(v uint64) {
	o.UsedBytes = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Licence) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Licence) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Licence) SetKind(v string) {
	o.Kind = &v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *Licence) GetCustomerName() string {
	if o == nil || o.CustomerName == nil {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetCustomerNameOk() (*string, bool) {
	if o == nil || o.CustomerName == nil {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *Licence) HasCustomerName() bool {
	if o != nil && o.CustomerName != nil {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *Licence) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Licence) GetFeatures() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Licence) GetFeaturesOk() (*[]string, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return &o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *Licence) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *Licence) SetFeatures(v []string) {
	o.Features = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Licence) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Licence) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Licence) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Licence) SetVersion(v string) {
	o.Version = &v
}

func (o Licence) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClusterID != nil {
		toSerialize["clusterID"] = o.ClusterID
	}
	if o.ExpiresAt != nil {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if o.ClusterCapacityBytes != nil {
		toSerialize["clusterCapacityBytes"] = o.ClusterCapacityBytes
	}
	if o.UsedBytes != nil {
		toSerialize["usedBytes"] = o.UsedBytes
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.CustomerName != nil {
		toSerialize["customerName"] = o.CustomerName
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableLicence struct {
	value *Licence
	isSet bool
}

func (v NullableLicence) Get() *Licence {
	return v.value
}

func (v *NullableLicence) Set(val *Licence) {
	v.value = val
	v.isSet = true
}

func (v NullableLicence) IsSet() bool {
	return v.isSet
}

func (v *NullableLicence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicence(val *Licence) *NullableLicence {
	return &NullableLicence{value: val, isSet: true}
}

func (v NullableLicence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


