/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ResizeVolumeRequest struct for ResizeVolumeRequest
type ResizeVolumeRequest struct {
	// The desired new size for the volume in  bytes. This value cannot be less than  the current size of the volume. 
	SizeBytes *uint64 `json:"sizeBytes,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewResizeVolumeRequest instantiates a new ResizeVolumeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResizeVolumeRequest() *ResizeVolumeRequest {
	this := ResizeVolumeRequest{}
	return &this
}

// NewResizeVolumeRequestWithDefaults instantiates a new ResizeVolumeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResizeVolumeRequestWithDefaults() *ResizeVolumeRequest {
	this := ResizeVolumeRequest{}
	return &this
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise.
func (o *ResizeVolumeRequest) GetSizeBytes() uint64 {
	if o == nil || o.SizeBytes == nil {
		var ret uint64
		return ret
	}
	return *o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResizeVolumeRequest) GetSizeBytesOk() (*uint64, bool) {
	if o == nil || o.SizeBytes == nil {
		return nil, false
	}
	return o.SizeBytes, true
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *ResizeVolumeRequest) HasSizeBytes() bool {
	if o != nil && o.SizeBytes != nil {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given uint64 and assigns it to the SizeBytes field.
func (o *ResizeVolumeRequest) SetSizeBytes(v uint64) {
	o.SizeBytes = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResizeVolumeRequest) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResizeVolumeRequest) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResizeVolumeRequest) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ResizeVolumeRequest) SetVersion(v string) {
	o.Version = &v
}

func (o ResizeVolumeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SizeBytes != nil {
		toSerialize["sizeBytes"] = o.SizeBytes
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableResizeVolumeRequest struct {
	value *ResizeVolumeRequest
	isSet bool
}

func (v NullableResizeVolumeRequest) Get() *ResizeVolumeRequest {
	return v.value
}

func (v *NullableResizeVolumeRequest) Set(val *ResizeVolumeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResizeVolumeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResizeVolumeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResizeVolumeRequest(val *ResizeVolumeRequest) *NullableResizeVolumeRequest {
	return &NullableResizeVolumeRequest{value: val, isSet: true}
}

func (v NullableResizeVolumeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResizeVolumeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


