/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// AttachVolumeData struct for AttachVolumeData
type AttachVolumeData struct {
	// A unique identifier for a node. The format of this type is undefined and may change but the defined properties will not change. 
	NodeID *string `json:"nodeID,omitempty"`
}

// NewAttachVolumeData instantiates a new AttachVolumeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachVolumeData() *AttachVolumeData {
	this := AttachVolumeData{}
	return &this
}

// NewAttachVolumeDataWithDefaults instantiates a new AttachVolumeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachVolumeDataWithDefaults() *AttachVolumeData {
	this := AttachVolumeData{}
	return &this
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *AttachVolumeData) GetNodeID() string {
	if o == nil || o.NodeID == nil {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachVolumeData) GetNodeIDOk() (*string, bool) {
	if o == nil || o.NodeID == nil {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *AttachVolumeData) HasNodeID() bool {
	if o != nil && o.NodeID != nil {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *AttachVolumeData) SetNodeID(v string) {
	o.NodeID = &v
}

func (o AttachVolumeData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NodeID != nil {
		toSerialize["nodeID"] = o.NodeID
	}
	return json.Marshal(toSerialize)
}

type NullableAttachVolumeData struct {
	value *AttachVolumeData
	isSet bool
}

func (v NullableAttachVolumeData) Get() *AttachVolumeData {
	return v.value
}

func (v *NullableAttachVolumeData) Set(val *AttachVolumeData) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachVolumeData) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachVolumeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachVolumeData(val *AttachVolumeData) *NullableAttachVolumeData {
	return &NullableAttachVolumeData{value: val, isSet: true}
}

func (v NullableAttachVolumeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachVolumeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


