/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Strategy The logic to use when placing the volume replicas across the available nodes. Possible options for this field include an availability zone aware rule and recommended rule in which multiple factors like available disk space, recent number of errors on the nodes, etc, are taken into consideration. Defaults to using a recommended placement strategy. 
type Strategy struct {
	Strategy *string `json:"strategy,omitempty"`
	Options NullableStrategyOptions `json:"options,omitempty"`
}

// NewStrategy instantiates a new Strategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategy() *Strategy {
	this := Strategy{}
	var strategy string = "recommended"
	this.Strategy = &strategy
	return &this
}

// NewStrategyWithDefaults instantiates a new Strategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyWithDefaults() *Strategy {
	this := Strategy{}
	var strategy string = "recommended"
	this.Strategy = &strategy
	return &this
}

// GetStrategy returns the Strategy field value if set, zero value otherwise.
func (o *Strategy) GetStrategy() string {
	if o == nil || o.Strategy == nil {
		var ret string
		return ret
	}
	return *o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Strategy) GetStrategyOk() (*string, bool) {
	if o == nil || o.Strategy == nil {
		return nil, false
	}
	return o.Strategy, true
}

// HasStrategy returns a boolean if a field has been set.
func (o *Strategy) HasStrategy() bool {
	if o != nil && o.Strategy != nil {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given string and assigns it to the Strategy field.
func (o *Strategy) SetStrategy(v string) {
	o.Strategy = &v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Strategy) GetOptions() StrategyOptions {
	if o == nil || o.Options.Get() == nil {
		var ret StrategyOptions
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Strategy) GetOptionsOk() (*StrategyOptions, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *Strategy) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableStrategyOptions and assigns it to the Options field.
func (o *Strategy) SetOptions(v StrategyOptions) {
	o.Options.Set(&v)
}
// SetOptionsNil sets the value for Options to be an explicit nil
func (o *Strategy) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *Strategy) UnsetOptions() {
	o.Options.Unset()
}

func (o Strategy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Strategy != nil {
		toSerialize["strategy"] = o.Strategy
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableStrategy struct {
	value *Strategy
	isSet bool
}

func (v NullableStrategy) Get() *Strategy {
	return v.value
}

func (v *NullableStrategy) Set(val *Strategy) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategy(val *Strategy) *NullableStrategy {
	return &NullableStrategy{value: val, isSet: true}
}

func (v NullableStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


