/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// AcceptedMessage struct for AcceptedMessage
type AcceptedMessage struct {
	Msg *string `json:"msg,omitempty"`
}

// NewAcceptedMessage instantiates a new AcceptedMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptedMessage() *AcceptedMessage {
	this := AcceptedMessage{}
	return &this
}

// NewAcceptedMessageWithDefaults instantiates a new AcceptedMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptedMessageWithDefaults() *AcceptedMessage {
	this := AcceptedMessage{}
	return &this
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *AcceptedMessage) GetMsg() string {
	if o == nil || o.Msg == nil {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcceptedMessage) GetMsgOk() (*string, bool) {
	if o == nil || o.Msg == nil {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *AcceptedMessage) HasMsg() bool {
	if o != nil && o.Msg != nil {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *AcceptedMessage) SetMsg(v string) {
	o.Msg = &v
}

func (o AcceptedMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	return json.Marshal(toSerialize)
}

type NullableAcceptedMessage struct {
	value *AcceptedMessage
	isSet bool
}

func (v NullableAcceptedMessage) Get() *AcceptedMessage {
	return v.value
}

func (v *NullableAcceptedMessage) Set(val *AcceptedMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptedMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptedMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptedMessage(val *AcceptedMessage) *NullableAcceptedMessage {
	return &NullableAcceptedMessage{value: val, isSet: true}
}

func (v NullableAcceptedMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptedMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


