/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateNamespaceData struct for CreateNamespaceData
type CreateNamespaceData struct {
	// The name of the namespace shown in the CLI and UI 
	Name *string `json:"name,omitempty"`
	// A set of arbitrary key value labels to apply to the entity. 
	Labels *map[string]string `json:"labels,omitempty"`
}

// NewCreateNamespaceData instantiates a new CreateNamespaceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNamespaceData() *CreateNamespaceData {
	this := CreateNamespaceData{}
	return &this
}

// NewCreateNamespaceDataWithDefaults instantiates a new CreateNamespaceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNamespaceDataWithDefaults() *CreateNamespaceData {
	this := CreateNamespaceData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateNamespaceData) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNamespaceData) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateNamespaceData) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateNamespaceData) SetName(v string) {
	o.Name = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateNamespaceData) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNamespaceData) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateNamespaceData) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateNamespaceData) SetLabels(v map[string]string) {
	o.Labels = &v
}

func (o CreateNamespaceData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	return json.Marshal(toSerialize)
}

type NullableCreateNamespaceData struct {
	value *CreateNamespaceData
	isSet bool
}

func (v NullableCreateNamespaceData) Get() *CreateNamespaceData {
	return v.value
}

func (v *NullableCreateNamespaceData) Set(val *CreateNamespaceData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNamespaceData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNamespaceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNamespaceData(val *CreateNamespaceData) *NullableCreateNamespaceData {
	return &NullableCreateNamespaceData{value: val, isSet: true}
}

func (v NullableCreateNamespaceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNamespaceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


