/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// AuthUserData struct for AuthUserData
type AuthUserData struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
