/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NFSVolumeMountEndpoint struct for NFSVolumeMountEndpoint
type NFSVolumeMountEndpoint struct {
	// The address to which the NFS server is bound. 
	MountEndpoint *string `json:"mountEndpoint,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewNFSVolumeMountEndpoint instantiates a new NFSVolumeMountEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNFSVolumeMountEndpoint() *NFSVolumeMountEndpoint {
	this := NFSVolumeMountEndpoint{}
	var mountEndpoint string = ""
	this.MountEndpoint = &mountEndpoint
	return &this
}

// NewNFSVolumeMountEndpointWithDefaults instantiates a new NFSVolumeMountEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNFSVolumeMountEndpointWithDefaults() *NFSVolumeMountEndpoint {
	this := NFSVolumeMountEndpoint{}
	var mountEndpoint string = ""
	this.MountEndpoint = &mountEndpoint
	return &this
}

// GetMountEndpoint returns the MountEndpoint field value if set, zero value otherwise.
func (o *NFSVolumeMountEndpoint) GetMountEndpoint() string {
	if o == nil || o.MountEndpoint == nil {
		var ret string
		return ret
	}
	return *o.MountEndpoint
}

// GetMountEndpointOk returns a tuple with the MountEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NFSVolumeMountEndpoint) GetMountEndpointOk() (*string, bool) {
	if o == nil || o.MountEndpoint == nil {
		return nil, false
	}
	return o.MountEndpoint, true
}

// HasMountEndpoint returns a boolean if a field has been set.
func (o *NFSVolumeMountEndpoint) HasMountEndpoint() bool {
	if o != nil && o.MountEndpoint != nil {
		return true
	}

	return false
}

// SetMountEndpoint gets a reference to the given string and assigns it to the MountEndpoint field.
func (o *NFSVolumeMountEndpoint) SetMountEndpoint(v string) {
	o.MountEndpoint = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *NFSVolumeMountEndpoint) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NFSVolumeMountEndpoint) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *NFSVolumeMountEndpoint) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *NFSVolumeMountEndpoint) SetVersion(v string) {
	o.Version = &v
}

func (o NFSVolumeMountEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MountEndpoint != nil {
		toSerialize["mountEndpoint"] = o.MountEndpoint
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableNFSVolumeMountEndpoint struct {
	value *NFSVolumeMountEndpoint
	isSet bool
}

func (v NullableNFSVolumeMountEndpoint) Get() *NFSVolumeMountEndpoint {
	return v.value
}

func (v *NullableNFSVolumeMountEndpoint) Set(val *NFSVolumeMountEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableNFSVolumeMountEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableNFSVolumeMountEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNFSVolumeMountEndpoint(val *NFSVolumeMountEndpoint) *NullableNFSVolumeMountEndpoint {
	return &NullableNFSVolumeMountEndpoint{value: val, isSet: true}
}

func (v NullableNFSVolumeMountEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNFSVolumeMountEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


