/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// AttachType The attachment type of a volume. \"host\" indicates that the volume is consumed by the node it is attached to. 
type AttachType string

// List of AttachType
const (
	ATTACHTYPE_UNKNOWN AttachType = "unknown"
	ATTACHTYPE_DETACHED AttachType = "detached"
	ATTACHTYPE_NFS AttachType = "nfs"
	ATTACHTYPE_HOST AttachType = "host"
)

// All allowed values of AttachType enum
var AllowedAttachTypeEnumValues = []AttachType{
	"unknown",
	"detached",
	"nfs",
	"host",
}

func (v *AttachType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AttachType(value)
	for _, existing := range AllowedAttachTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AttachType", value)
}

// NewAttachTypeFromValue returns a pointer to a valid AttachType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAttachTypeFromValue(v string) (*AttachType, error) {
	ev := AttachType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AttachType: valid values are %v", v, AllowedAttachTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AttachType) IsValid() bool {
	for _, existing := range AllowedAttachTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AttachType value
func (v AttachType) Ptr() *AttachType {
	return &v
}

type NullableAttachType struct {
	value *AttachType
	isSet bool
}

func (v NullableAttachType) Get() *AttachType {
	return v.value
}

func (v *NullableAttachType) Set(val *AttachType) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachType) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachType(val *AttachType) *NullableAttachType {
	return &NullableAttachType{value: val, isSet: true}
}

func (v NullableAttachType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

