/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// FailureModeIntent The intent-based failure mode behaviour of a volume. The default behaviour for a volume is \"hard\", in the absence of a directly  configured intent or numerical failure threshold.  
type FailureModeIntent string

// List of FailureModeIntent
const (
	FAILUREMODEINTENT_HARD FailureModeIntent = "hard"
	FAILUREMODEINTENT_SOFT FailureModeIntent = "soft"
	FAILUREMODEINTENT_ALWAYSON FailureModeIntent = "alwayson"
)

// All allowed values of FailureModeIntent enum
var AllowedFailureModeIntentEnumValues = []FailureModeIntent{
	"hard",
	"soft",
	"alwayson",
}

func (v *FailureModeIntent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FailureModeIntent(value)
	for _, existing := range AllowedFailureModeIntentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FailureModeIntent", value)
}

// NewFailureModeIntentFromValue returns a pointer to a valid FailureModeIntent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFailureModeIntentFromValue(v string) (*FailureModeIntent, error) {
	ev := FailureModeIntent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FailureModeIntent: valid values are %v", v, AllowedFailureModeIntentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FailureModeIntent) IsValid() bool {
	for _, existing := range AllowedFailureModeIntentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FailureModeIntent value
func (v FailureModeIntent) Ptr() *FailureModeIntent {
	return &v
}

type NullableFailureModeIntent struct {
	value *FailureModeIntent
	isSet bool
}

func (v NullableFailureModeIntent) Get() *FailureModeIntent {
	return v.value
}

func (v *NullableFailureModeIntent) Set(val *FailureModeIntent) {
	v.value = val
	v.isSet = true
}

func (v NullableFailureModeIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableFailureModeIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFailureModeIntent(val *FailureModeIntent) *NullableFailureModeIntent {
	return &NullableFailureModeIntent{value: val, isSet: true}
}

func (v NullableFailureModeIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFailureModeIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

