/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateNamespaceData struct for UpdateNamespaceData
type UpdateNamespaceData struct {
	// A set of arbitrary key value labels to apply to the entity. 
	Labels *map[string]string `json:"labels,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdateNamespaceData instantiates a new UpdateNamespaceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNamespaceData() *UpdateNamespaceData {
	this := UpdateNamespaceData{}
	return &this
}

// NewUpdateNamespaceDataWithDefaults instantiates a new UpdateNamespaceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNamespaceDataWithDefaults() *UpdateNamespaceData {
	this := UpdateNamespaceData{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateNamespaceData) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNamespaceData) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UpdateNamespaceData) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *UpdateNamespaceData) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateNamespaceData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNamespaceData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateNamespaceData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateNamespaceData) SetVersion(v string) {
	o.Version = &v
}

func (o UpdateNamespaceData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateNamespaceData struct {
	value *UpdateNamespaceData
	isSet bool
}

func (v NullableUpdateNamespaceData) Get() *UpdateNamespaceData {
	return v.value
}

func (v *NullableUpdateNamespaceData) Set(val *UpdateNamespaceData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNamespaceData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNamespaceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNamespaceData(val *UpdateNamespaceData) *NullableUpdateNamespaceData {
	return &NullableUpdateNamespaceData{value: val, isSet: true}
}

func (v NullableUpdateNamespaceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNamespaceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


