/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SyncProgress The progress report for an ongoing sync.  
type SyncProgress struct {
	// Number of bytes left remaining to complete the sync. 
	BytesRemaining *uint64 `json:"bytesRemaining,omitempty"`
	// The average throughput of the sync given as bytes per  second. 
	ThroughputBytes *uint64 `json:"throughputBytes,omitempty"`
	// The estimated time left for the sync to complete, given in seconds. When this field has a value of 0 either the  sync is complete or no duration estimate could be made. The values reported for bytesRemaining and  throughputBytes provide the client with the information needed to choose what to display. 
	EstimatedSecondsRemaining *uint64 `json:"estimatedSecondsRemaining,omitempty"`
}

// NewSyncProgress instantiates a new SyncProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncProgress() *SyncProgress {
	this := SyncProgress{}
	return &this
}

// NewSyncProgressWithDefaults instantiates a new SyncProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncProgressWithDefaults() *SyncProgress {
	this := SyncProgress{}
	return &this
}

// GetBytesRemaining returns the BytesRemaining field value if set, zero value otherwise.
func (o *SyncProgress) GetBytesRemaining() uint64 {
	if o == nil || o.BytesRemaining == nil {
		var ret uint64
		return ret
	}
	return *o.BytesRemaining
}

// GetBytesRemainingOk returns a tuple with the BytesRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncProgress) GetBytesRemainingOk() (*uint64, bool) {
	if o == nil || o.BytesRemaining == nil {
		return nil, false
	}
	return o.BytesRemaining, true
}

// HasBytesRemaining returns a boolean if a field has been set.
func (o *SyncProgress) HasBytesRemaining() bool {
	if o != nil && o.BytesRemaining != nil {
		return true
	}

	return false
}

// SetBytesRemaining gets a reference to the given uint64 and assigns it to the BytesRemaining field.
func (o *SyncProgress) SetBytesRemaining(v uint64) {
	o.BytesRemaining = &v
}

// GetThroughputBytes returns the ThroughputBytes field value if set, zero value otherwise.
func (o *SyncProgress) GetThroughputBytes() uint64 {
	if o == nil || o.ThroughputBytes == nil {
		var ret uint64
		return ret
	}
	return *o.ThroughputBytes
}

// GetThroughputBytesOk returns a tuple with the ThroughputBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncProgress) GetThroughputBytesOk() (*uint64, bool) {
	if o == nil || o.ThroughputBytes == nil {
		return nil, false
	}
	return o.ThroughputBytes, true
}

// HasThroughputBytes returns a boolean if a field has been set.
func (o *SyncProgress) HasThroughputBytes() bool {
	if o != nil && o.ThroughputBytes != nil {
		return true
	}

	return false
}

// SetThroughputBytes gets a reference to the given uint64 and assigns it to the ThroughputBytes field.
func (o *SyncProgress) SetThroughputBytes(v uint64) {
	o.ThroughputBytes = &v
}

// GetEstimatedSecondsRemaining returns the EstimatedSecondsRemaining field value if set, zero value otherwise.
func (o *SyncProgress) GetEstimatedSecondsRemaining() uint64 {
	if o == nil || o.EstimatedSecondsRemaining == nil {
		var ret uint64
		return ret
	}
	return *o.EstimatedSecondsRemaining
}

// GetEstimatedSecondsRemainingOk returns a tuple with the EstimatedSecondsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncProgress) GetEstimatedSecondsRemainingOk() (*uint64, bool) {
	if o == nil || o.EstimatedSecondsRemaining == nil {
		return nil, false
	}
	return o.EstimatedSecondsRemaining, true
}

// HasEstimatedSecondsRemaining returns a boolean if a field has been set.
func (o *SyncProgress) HasEstimatedSecondsRemaining() bool {
	if o != nil && o.EstimatedSecondsRemaining != nil {
		return true
	}

	return false
}

// SetEstimatedSecondsRemaining gets a reference to the given uint64 and assigns it to the EstimatedSecondsRemaining field.
func (o *SyncProgress) SetEstimatedSecondsRemaining(v uint64) {
	o.EstimatedSecondsRemaining = &v
}

func (o SyncProgress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BytesRemaining != nil {
		toSerialize["bytesRemaining"] = o.BytesRemaining
	}
	if o.ThroughputBytes != nil {
		toSerialize["throughputBytes"] = o.ThroughputBytes
	}
	if o.EstimatedSecondsRemaining != nil {
		toSerialize["estimatedSecondsRemaining"] = o.EstimatedSecondsRemaining
	}
	return json.Marshal(toSerialize)
}

type NullableSyncProgress struct {
	value *SyncProgress
	isSet bool
}

func (v NullableSyncProgress) Get() *SyncProgress {
	return v.value
}

func (v *NullableSyncProgress) Set(val *SyncProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncProgress(val *SyncProgress) *NullableSyncProgress {
	return &NullableSyncProgress{value: val, isSet: true}
}

func (v NullableSyncProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


