/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SetPlacementStrategyData struct for SetPlacementStrategyData
type SetPlacementStrategyData struct {
	PlacementStrategy *Strategy `json:"placementStrategy,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewSetPlacementStrategyData instantiates a new SetPlacementStrategyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetPlacementStrategyData() *SetPlacementStrategyData {
	this := SetPlacementStrategyData{}
	return &this
}

// NewSetPlacementStrategyDataWithDefaults instantiates a new SetPlacementStrategyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetPlacementStrategyDataWithDefaults() *SetPlacementStrategyData {
	this := SetPlacementStrategyData{}
	return &this
}

// GetPlacementStrategy returns the PlacementStrategy field value if set, zero value otherwise.
func (o *SetPlacementStrategyData) GetPlacementStrategy() Strategy {
	if o == nil || o.PlacementStrategy == nil {
		var ret Strategy
		return ret
	}
	return *o.PlacementStrategy
}

// GetPlacementStrategyOk returns a tuple with the PlacementStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetPlacementStrategyData) GetPlacementStrategyOk() (*Strategy, bool) {
	if o == nil || o.PlacementStrategy == nil {
		return nil, false
	}
	return o.PlacementStrategy, true
}

// HasPlacementStrategy returns a boolean if a field has been set.
func (o *SetPlacementStrategyData) HasPlacementStrategy() bool {
	if o != nil && o.PlacementStrategy != nil {
		return true
	}

	return false
}

// SetPlacementStrategy gets a reference to the given Strategy and assigns it to the PlacementStrategy field.
func (o *SetPlacementStrategyData) SetPlacementStrategy(v Strategy) {
	o.PlacementStrategy = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SetPlacementStrategyData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetPlacementStrategyData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SetPlacementStrategyData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SetPlacementStrategyData) SetVersion(v string) {
	o.Version = &v
}

func (o SetPlacementStrategyData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PlacementStrategy != nil {
		toSerialize["placementStrategy"] = o.PlacementStrategy
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableSetPlacementStrategyData struct {
	value *SetPlacementStrategyData
	isSet bool
}

func (v NullableSetPlacementStrategyData) Get() *SetPlacementStrategyData {
	return v.value
}

func (v *NullableSetPlacementStrategyData) Set(val *SetPlacementStrategyData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetPlacementStrategyData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetPlacementStrategyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetPlacementStrategyData(val *SetPlacementStrategyData) *NullableSetPlacementStrategyData {
	return &NullableSetPlacementStrategyData{value: val, isSet: true}
}

func (v NullableSetPlacementStrategyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetPlacementStrategyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


