/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeploymentInfo struct for DeploymentInfo
type DeploymentInfo struct {
	// A unique identifier for a volume deployment. The format of this type is undefined and may change but the defined properties will not change. 
	Id *string `json:"id,omitempty"`
	// A unique identifier for a node. The format of this type is undefined and may change but the defined properties will not change. 
	NodeID *string `json:"nodeID,omitempty"`
	// The hostname of the node that is hosting the deployment 
	Hostname *string `json:"hostname,omitempty"`
	// Indicates if the volume deployment is eligible for promotion 
	Promotable *bool `json:"promotable,omitempty"`
}

// NewDeploymentInfo instantiates a new DeploymentInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentInfo() *DeploymentInfo {
	this := DeploymentInfo{}
	return &this
}

// NewDeploymentInfoWithDefaults instantiates a new DeploymentInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentInfoWithDefaults() *DeploymentInfo {
	this := DeploymentInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeploymentInfo) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentInfo) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeploymentInfo) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeploymentInfo) SetId(v string) {
	o.Id = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *DeploymentInfo) GetNodeID() string {
	if o == nil || o.NodeID == nil {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentInfo) GetNodeIDOk() (*string, bool) {
	if o == nil || o.NodeID == nil {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *DeploymentInfo) HasNodeID() bool {
	if o != nil && o.NodeID != nil {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *DeploymentInfo) SetNodeID(v string) {
	o.NodeID = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *DeploymentInfo) GetHostname() string {
	if o == nil || o.Hostname == nil {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentInfo) GetHostnameOk() (*string, bool) {
	if o == nil || o.Hostname == nil {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *DeploymentInfo) HasHostname() bool {
	if o != nil && o.Hostname != nil {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *DeploymentInfo) SetHostname(v string) {
	o.Hostname = &v
}

// GetPromotable returns the Promotable field value if set, zero value otherwise.
func (o *DeploymentInfo) GetPromotable() bool {
	if o == nil || o.Promotable == nil {
		var ret bool
		return ret
	}
	return *o.Promotable
}

// GetPromotableOk returns a tuple with the Promotable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentInfo) GetPromotableOk() (*bool, bool) {
	if o == nil || o.Promotable == nil {
		return nil, false
	}
	return o.Promotable, true
}

// HasPromotable returns a boolean if a field has been set.
func (o *DeploymentInfo) HasPromotable() bool {
	if o != nil && o.Promotable != nil {
		return true
	}

	return false
}

// SetPromotable gets a reference to the given bool and assigns it to the Promotable field.
func (o *DeploymentInfo) SetPromotable(v bool) {
	o.Promotable = &v
}

func (o DeploymentInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.NodeID != nil {
		toSerialize["nodeID"] = o.NodeID
	}
	if o.Hostname != nil {
		toSerialize["hostname"] = o.Hostname
	}
	if o.Promotable != nil {
		toSerialize["promotable"] = o.Promotable
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentInfo struct {
	value *DeploymentInfo
	isSet bool
}

func (v NullableDeploymentInfo) Get() *DeploymentInfo {
	return v.value
}

func (v *NullableDeploymentInfo) Set(val *DeploymentInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentInfo(val *DeploymentInfo) *NullableDeploymentInfo {
	return &NullableDeploymentInfo{value: val, isSet: true}
}

func (v NullableDeploymentInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


