/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateLicence struct for UpdateLicence
type UpdateLicence struct {
	// A StorageOS product licence key, used to register a cluster. The format of this type is opaque and may change. 
	Key *string `json:"key,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdateLicence instantiates a new UpdateLicence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLicence() *UpdateLicence {
	this := UpdateLicence{}
	return &this
}

// NewUpdateLicenceWithDefaults instantiates a new UpdateLicence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLicenceWithDefaults() *UpdateLicence {
	this := UpdateLicence{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *UpdateLicence) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLicence) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *UpdateLicence) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *UpdateLicence) SetKey(v string) {
	o.Key = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateLicence) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLicence) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateLicence) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateLicence) SetVersion(v string) {
	o.Version = &v
}

func (o UpdateLicence) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateLicence struct {
	value *UpdateLicence
	isSet bool
}

func (v NullableUpdateLicence) Get() *UpdateLicence {
	return v.value
}

func (v *NullableUpdateLicence) Set(val *UpdateLicence) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLicence) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLicence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLicence(val *UpdateLicence) *NullableUpdateLicence {
	return &NullableUpdateLicence{value: val, isSet: true}
}

func (v NullableUpdateLicence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLicence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


