/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// AcceptedMessage struct for AcceptedMessage
type AcceptedMessage struct {
	Msg string `json:"msg,omitempty"`
}
