/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdatePolicyGroupData struct for UpdatePolicyGroupData
type UpdatePolicyGroupData struct {
	// A set of authorisation policies to apply to the policy group.
	Specs []PoliciesIdSpecs `json:"specs,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdatePolicyGroupData instantiates a new UpdatePolicyGroupData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePolicyGroupData() *UpdatePolicyGroupData {
	this := UpdatePolicyGroupData{}
	return &this
}

// NewUpdatePolicyGroupDataWithDefaults instantiates a new UpdatePolicyGroupData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePolicyGroupDataWithDefaults() *UpdatePolicyGroupData {
	this := UpdatePolicyGroupData{}
	return &this
}

// GetSpecs returns the Specs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePolicyGroupData) GetSpecs() []PoliciesIdSpecs {
	if o == nil  {
		var ret []PoliciesIdSpecs
		return ret
	}
	return o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePolicyGroupData) GetSpecsOk() (*[]PoliciesIdSpecs, bool) {
	if o == nil || o.Specs == nil {
		return nil, false
	}
	return &o.Specs, true
}

// HasSpecs returns a boolean if a field has been set.
func (o *UpdatePolicyGroupData) HasSpecs() bool {
	if o != nil && o.Specs != nil {
		return true
	}

	return false
}

// SetSpecs gets a reference to the given []PoliciesIdSpecs and assigns it to the Specs field.
func (o *UpdatePolicyGroupData) SetSpecs(v []PoliciesIdSpecs) {
	o.Specs = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdatePolicyGroupData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePolicyGroupData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdatePolicyGroupData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdatePolicyGroupData) SetVersion(v string) {
	o.Version = &v
}

func (o UpdatePolicyGroupData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Specs != nil {
		toSerialize["specs"] = o.Specs
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdatePolicyGroupData struct {
	value *UpdatePolicyGroupData
	isSet bool
}

func (v NullableUpdatePolicyGroupData) Get() *UpdatePolicyGroupData {
	return v.value
}

func (v *NullableUpdatePolicyGroupData) Set(val *UpdatePolicyGroupData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePolicyGroupData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePolicyGroupData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePolicyGroupData(val *UpdatePolicyGroupData) *NullableUpdatePolicyGroupData {
	return &NullableUpdatePolicyGroupData{value: val, isSet: true}
}

func (v NullableUpdatePolicyGroupData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePolicyGroupData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


