/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ReplicaHealth The operational health of a volume replica deployment 
type ReplicaHealth string

// List of ReplicaHealth
const (
	REPLICAHEALTH_RECOVERING ReplicaHealth = "recovering"
	REPLICAHEALTH_PROVISIONING ReplicaHealth = "provisioning"
	REPLICAHEALTH_PROVISIONED ReplicaHealth = "provisioned"
	REPLICAHEALTH_SYNCING ReplicaHealth = "syncing"
	REPLICAHEALTH_READY ReplicaHealth = "ready"
	REPLICAHEALTH_DELETED ReplicaHealth = "deleted"
	REPLICAHEALTH_FAILED ReplicaHealth = "failed"
	REPLICAHEALTH_UNKNOWN ReplicaHealth = "unknown"
)

// All allowed values of ReplicaHealth enum
var AllowedReplicaHealthEnumValues = []ReplicaHealth{
	"recovering",
	"provisioning",
	"provisioned",
	"syncing",
	"ready",
	"deleted",
	"failed",
	"unknown",
}

func (v *ReplicaHealth) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReplicaHealth(value)
	for _, existing := range AllowedReplicaHealthEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReplicaHealth", value)
}

// NewReplicaHealthFromValue returns a pointer to a valid ReplicaHealth
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReplicaHealthFromValue(v string) (*ReplicaHealth, error) {
	ev := ReplicaHealth(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReplicaHealth: valid values are %v", v, AllowedReplicaHealthEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReplicaHealth) IsValid() bool {
	for _, existing := range AllowedReplicaHealthEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReplicaHealth value
func (v ReplicaHealth) Ptr() *ReplicaHealth {
	return &v
}

type NullableReplicaHealth struct {
	value *ReplicaHealth
	isSet bool
}

func (v NullableReplicaHealth) Get() *ReplicaHealth {
	return v.value
}

func (v *NullableReplicaHealth) Set(val *ReplicaHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableReplicaHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableReplicaHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplicaHealth(val *ReplicaHealth) *NullableReplicaHealth {
	return &NullableReplicaHealth{value: val, isSet: true}
}

func (v NullableReplicaHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplicaHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

