/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PolicyGroupUsers struct for PolicyGroupUsers
type PolicyGroupUsers struct {
	// A unique identifier for a user. The format of this type is undefined and may change but the defined properties will not change.. 
	Id *string `json:"id,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewPolicyGroupUsers instantiates a new PolicyGroupUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyGroupUsers() *PolicyGroupUsers {
	this := PolicyGroupUsers{}
	return &this
}

// NewPolicyGroupUsersWithDefaults instantiates a new PolicyGroupUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyGroupUsersWithDefaults() *PolicyGroupUsers {
	this := PolicyGroupUsers{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PolicyGroupUsers) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyGroupUsers) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PolicyGroupUsers) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PolicyGroupUsers) SetId(v string) {
	o.Id = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PolicyGroupUsers) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyGroupUsers) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PolicyGroupUsers) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PolicyGroupUsers) SetUsername(v string) {
	o.Username = &v
}

func (o PolicyGroupUsers) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	return json.Marshal(toSerialize)
}

type NullablePolicyGroupUsers struct {
	value *PolicyGroupUsers
	isSet bool
}

func (v NullablePolicyGroupUsers) Get() *PolicyGroupUsers {
	return v.value
}

func (v *NullablePolicyGroupUsers) Set(val *PolicyGroupUsers) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyGroupUsers) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyGroupUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyGroupUsers(val *PolicyGroupUsers) *NullablePolicyGroupUsers {
	return &NullablePolicyGroupUsers{value: val, isSet: true}
}

func (v NullablePolicyGroupUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyGroupUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


