/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SetComputeOnlyNodeData struct for SetComputeOnlyNodeData
type SetComputeOnlyNodeData struct {
	// Marks the node's desired configuration  state as compute-only. This will result in the node being avoided for volume placement 
	ComputeOnly *bool `json:"computeOnly,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewSetComputeOnlyNodeData instantiates a new SetComputeOnlyNodeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetComputeOnlyNodeData() *SetComputeOnlyNodeData {
	this := SetComputeOnlyNodeData{}
	return &this
}

// NewSetComputeOnlyNodeDataWithDefaults instantiates a new SetComputeOnlyNodeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetComputeOnlyNodeDataWithDefaults() *SetComputeOnlyNodeData {
	this := SetComputeOnlyNodeData{}
	return &this
}

// GetComputeOnly returns the ComputeOnly field value if set, zero value otherwise.
func (o *SetComputeOnlyNodeData) GetComputeOnly() bool {
	if o == nil || o.ComputeOnly == nil {
		var ret bool
		return ret
	}
	return *o.ComputeOnly
}

// GetComputeOnlyOk returns a tuple with the ComputeOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetComputeOnlyNodeData) GetComputeOnlyOk() (*bool, bool) {
	if o == nil || o.ComputeOnly == nil {
		return nil, false
	}
	return o.ComputeOnly, true
}

// HasComputeOnly returns a boolean if a field has been set.
func (o *SetComputeOnlyNodeData) HasComputeOnly() bool {
	if o != nil && o.ComputeOnly != nil {
		return true
	}

	return false
}

// SetComputeOnly gets a reference to the given bool and assigns it to the ComputeOnly field.
func (o *SetComputeOnlyNodeData) SetComputeOnly(v bool) {
	o.ComputeOnly = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SetComputeOnlyNodeData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetComputeOnlyNodeData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SetComputeOnlyNodeData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SetComputeOnlyNodeData) SetVersion(v string) {
	o.Version = &v
}

func (o SetComputeOnlyNodeData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ComputeOnly != nil {
		toSerialize["computeOnly"] = o.ComputeOnly
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableSetComputeOnlyNodeData struct {
	value *SetComputeOnlyNodeData
	isSet bool
}

func (v NullableSetComputeOnlyNodeData) Get() *SetComputeOnlyNodeData {
	return v.value
}

func (v *NullableSetComputeOnlyNodeData) Set(val *SetComputeOnlyNodeData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetComputeOnlyNodeData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetComputeOnlyNodeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetComputeOnlyNodeData(val *SetComputeOnlyNodeData) *NullableSetComputeOnlyNodeData {
	return &NullableSetComputeOnlyNodeData{value: val, isSet: true}
}

func (v NullableSetComputeOnlyNodeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetComputeOnlyNodeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


