/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateUserData struct for UpdateUserData
type UpdateUserData struct {
	// If not present, the existing password is not changed
	Password *string `json:"password,omitempty"`
	// If true, this user is an administrator of the cluster. Administrators bypass the usual authentication checks and are granted access to all resources. Some actions (such as adding a new user) can only be performed by an administrator. 
	IsAdmin *bool `json:"isAdmin,omitempty"`
	// Defines a set of policy group IDs this user is a member of. Policy groups can be used to logically group users and apply authorisation  policies to all members. 
	Groups []string `json:"groups,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdateUserData instantiates a new UpdateUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserData() *UpdateUserData {
	this := UpdateUserData{}
	var password string = "unchanged"
	this.Password = &password
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// NewUpdateUserDataWithDefaults instantiates a new UpdateUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserDataWithDefaults() *UpdateUserData {
	this := UpdateUserData{}
	var password string = "unchanged"
	this.Password = &password
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UpdateUserData) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UpdateUserData) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UpdateUserData) SetPassword(v string) {
	o.Password = &v
}

// GetIsAdmin returns the IsAdmin field value if set, zero value otherwise.
func (o *UpdateUserData) GetIsAdmin() bool {
	if o == nil || o.IsAdmin == nil {
		var ret bool
		return ret
	}
	return *o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetIsAdminOk() (*bool, bool) {
	if o == nil || o.IsAdmin == nil {
		return nil, false
	}
	return o.IsAdmin, true
}

// HasIsAdmin returns a boolean if a field has been set.
func (o *UpdateUserData) HasIsAdmin() bool {
	if o != nil && o.IsAdmin != nil {
		return true
	}

	return false
}

// SetIsAdmin gets a reference to the given bool and assigns it to the IsAdmin field.
func (o *UpdateUserData) SetIsAdmin(v bool) {
	o.IsAdmin = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateUserData) GetGroups() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateUserData) GetGroupsOk() (*[]string, bool) {
	if o == nil || o.Groups == nil {
		return nil, false
	}
	return &o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *UpdateUserData) HasGroups() bool {
	if o != nil && o.Groups != nil {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *UpdateUserData) SetGroups(v []string) {
	o.Groups = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateUserData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateUserData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateUserData) SetVersion(v string) {
	o.Version = &v
}

func (o UpdateUserData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.IsAdmin != nil {
		toSerialize["isAdmin"] = o.IsAdmin
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateUserData struct {
	value *UpdateUserData
	isSet bool
}

func (v NullableUpdateUserData) Get() *UpdateUserData {
	return v.value
}

func (v *NullableUpdateUserData) Set(val *UpdateUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserData(val *UpdateUserData) *NullableUpdateUserData {
	return &NullableUpdateUserData{value: val, isSet: true}
}

func (v NullableUpdateUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


