/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ReplicaDeploymentInfoAllOf struct for ReplicaDeploymentInfoAllOf
type ReplicaDeploymentInfoAllOf struct {
	Health *ReplicaHealth `json:"health,omitempty"`
	SyncProgress *SyncProgress `json:"syncProgress,omitempty"`
}

// NewReplicaDeploymentInfoAllOf instantiates a new ReplicaDeploymentInfoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplicaDeploymentInfoAllOf() *ReplicaDeploymentInfoAllOf {
	this := ReplicaDeploymentInfoAllOf{}
	return &this
}

// NewReplicaDeploymentInfoAllOfWithDefaults instantiates a new ReplicaDeploymentInfoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplicaDeploymentInfoAllOfWithDefaults() *ReplicaDeploymentInfoAllOf {
	this := ReplicaDeploymentInfoAllOf{}
	return &this
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfoAllOf) GetHealth() ReplicaHealth {
	if o == nil || o.Health == nil {
		var ret ReplicaHealth
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfoAllOf) GetHealthOk() (*ReplicaHealth, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfoAllOf) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given ReplicaHealth and assigns it to the Health field.
func (o *ReplicaDeploymentInfoAllOf) SetHealth(v ReplicaHealth) {
	o.Health = &v
}

// GetSyncProgress returns the SyncProgress field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfoAllOf) GetSyncProgress() SyncProgress {
	if o == nil || o.SyncProgress == nil {
		var ret SyncProgress
		return ret
	}
	return *o.SyncProgress
}

// GetSyncProgressOk returns a tuple with the SyncProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfoAllOf) GetSyncProgressOk() (*SyncProgress, bool) {
	if o == nil || o.SyncProgress == nil {
		return nil, false
	}
	return o.SyncProgress, true
}

// HasSyncProgress returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfoAllOf) HasSyncProgress() bool {
	if o != nil && o.SyncProgress != nil {
		return true
	}

	return false
}

// SetSyncProgress gets a reference to the given SyncProgress and assigns it to the SyncProgress field.
func (o *ReplicaDeploymentInfoAllOf) SetSyncProgress(v SyncProgress) {
	o.SyncProgress = &v
}

func (o ReplicaDeploymentInfoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	if o.SyncProgress != nil {
		toSerialize["syncProgress"] = o.SyncProgress
	}
	return json.Marshal(toSerialize)
}

type NullableReplicaDeploymentInfoAllOf struct {
	value *ReplicaDeploymentInfoAllOf
	isSet bool
}

func (v NullableReplicaDeploymentInfoAllOf) Get() *ReplicaDeploymentInfoAllOf {
	return v.value
}

func (v *NullableReplicaDeploymentInfoAllOf) Set(val *ReplicaDeploymentInfoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableReplicaDeploymentInfoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableReplicaDeploymentInfoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplicaDeploymentInfoAllOf(val *ReplicaDeploymentInfoAllOf) *NullableReplicaDeploymentInfoAllOf {
	return &NullableReplicaDeploymentInfoAllOf{value: val, isSet: true}
}

func (v NullableReplicaDeploymentInfoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplicaDeploymentInfoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


