/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateUserData struct for CreateUserData
type CreateUserData struct {
	Username string `json:"username"`
	// If not present, the existing password is not changed
	Password string `json:"password"`
	// If true, this user is an administrator of the cluster. Administrators bypass the usual authentication checks and are granted access to all resources. Some actions (such as adding a new user) can only be performed by an administrator. 
	IsAdmin *bool `json:"isAdmin,omitempty"`
	// Defines a set of policy group IDs this user is a member of. Policy groups can be used to logically group users and apply authorisation  policies to all members. 
	Groups []string `json:"groups,omitempty"`
}

// NewCreateUserData instantiates a new CreateUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserData(username string, password string) *CreateUserData {
	this := CreateUserData{}
	this.Username = username
	this.Password = password
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// NewCreateUserDataWithDefaults instantiates a new CreateUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserDataWithDefaults() *CreateUserData {
	this := CreateUserData{}
	var password string = "unchanged"
	this.Password = password
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// GetUsername returns the Username field value
func (o *CreateUserData) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateUserData) GetUsernameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateUserData) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *CreateUserData) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateUserData) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateUserData) SetPassword(v string) {
	o.Password = v
}

// GetIsAdmin returns the IsAdmin field value if set, zero value otherwise.
func (o *CreateUserData) GetIsAdmin() bool {
	if o == nil || o.IsAdmin == nil {
		var ret bool
		return ret
	}
	return *o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserData) GetIsAdminOk() (*bool, bool) {
	if o == nil || o.IsAdmin == nil {
		return nil, false
	}
	return o.IsAdmin, true
}

// HasIsAdmin returns a boolean if a field has been set.
func (o *CreateUserData) HasIsAdmin() bool {
	if o != nil && o.IsAdmin != nil {
		return true
	}

	return false
}

// SetIsAdmin gets a reference to the given bool and assigns it to the IsAdmin field.
func (o *CreateUserData) SetIsAdmin(v bool) {
	o.IsAdmin = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUserData) GetGroups() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUserData) GetGroupsOk() (*[]string, bool) {
	if o == nil || o.Groups == nil {
		return nil, false
	}
	return &o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *CreateUserData) HasGroups() bool {
	if o != nil && o.Groups != nil {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *CreateUserData) SetGroups(v []string) {
	o.Groups = v
}

func (o CreateUserData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["username"] = o.Username
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if o.IsAdmin != nil {
		toSerialize["isAdmin"] = o.IsAdmin
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	return json.Marshal(toSerialize)
}

type NullableCreateUserData struct {
	value *CreateUserData
	isSet bool
}

func (v NullableCreateUserData) Get() *CreateUserData {
	return v.value
}

func (v *NullableCreateUserData) Set(val *CreateUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserData(val *CreateUserData) *NullableCreateUserData {
	return &NullableCreateUserData{value: val, isSet: true}
}

func (v NullableCreateUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


