/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CapacityStats struct for CapacityStats
type CapacityStats struct {
	// Total bytes in the filesystem 
	Total *uint64 `json:"total,omitempty"`
	// Free bytes in the filesystem available to root user 
	Free *uint64 `json:"free,omitempty"`
	// Byte value available to an unprivileged user 
	Available *uint64 `json:"available,omitempty"`
}

// NewCapacityStats instantiates a new CapacityStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapacityStats() *CapacityStats {
	this := CapacityStats{}
	return &this
}

// NewCapacityStatsWithDefaults instantiates a new CapacityStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapacityStatsWithDefaults() *CapacityStats {
	this := CapacityStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *CapacityStats) GetTotal() uint64 {
	if o == nil || o.Total == nil {
		var ret uint64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityStats) GetTotalOk() (*uint64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *CapacityStats) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given uint64 and assigns it to the Total field.
func (o *CapacityStats) SetTotal(v uint64) {
	o.Total = &v
}

// GetFree returns the Free field value if set, zero value otherwise.
func (o *CapacityStats) GetFree() uint64 {
	if o == nil || o.Free == nil {
		var ret uint64
		return ret
	}
	return *o.Free
}

// GetFreeOk returns a tuple with the Free field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityStats) GetFreeOk() (*uint64, bool) {
	if o == nil || o.Free == nil {
		return nil, false
	}
	return o.Free, true
}

// HasFree returns a boolean if a field has been set.
func (o *CapacityStats) HasFree() bool {
	if o != nil && o.Free != nil {
		return true
	}

	return false
}

// SetFree gets a reference to the given uint64 and assigns it to the Free field.
func (o *CapacityStats) SetFree(v uint64) {
	o.Free = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *CapacityStats) GetAvailable() uint64 {
	if o == nil || o.Available == nil {
		var ret uint64
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityStats) GetAvailableOk() (*uint64, bool) {
	if o == nil || o.Available == nil {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *CapacityStats) HasAvailable() bool {
	if o != nil && o.Available != nil {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given uint64 and assigns it to the Available field.
func (o *CapacityStats) SetAvailable(v uint64) {
	o.Available = &v
}

func (o CapacityStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Free != nil {
		toSerialize["free"] = o.Free
	}
	if o.Available != nil {
		toSerialize["available"] = o.Available
	}
	return json.Marshal(toSerialize)
}

type NullableCapacityStats struct {
	value *CapacityStats
	isSet bool
}

func (v NullableCapacityStats) Get() *CapacityStats {
	return v.value
}

func (v *NullableCapacityStats) Set(val *CapacityStats) {
	v.value = val
	v.isSet = true
}

func (v NullableCapacityStats) IsSet() bool {
	return v.isSet
}

func (v *NullableCapacityStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapacityStats(val *CapacityStats) *NullableCapacityStats {
	return &NullableCapacityStats{value: val, isSet: true}
}

func (v NullableCapacityStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapacityStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


