/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// PolicyGroupUsers struct for PolicyGroupUsers
type PolicyGroupUsers struct {
	// A unique identifier for a user. The format of this type is undefined and may change but the defined properties will not change.. 
	Id string `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
}
