/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateAuthenticatedUserData struct for UpdateAuthenticatedUserData
type UpdateAuthenticatedUserData struct {
	// If not present, the existing password is not changed
	Password *string `json:"password,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdateAuthenticatedUserData instantiates a new UpdateAuthenticatedUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAuthenticatedUserData() *UpdateAuthenticatedUserData {
	this := UpdateAuthenticatedUserData{}
	var password string = "unchanged"
	this.Password = &password
	return &this
}

// NewUpdateAuthenticatedUserDataWithDefaults instantiates a new UpdateAuthenticatedUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAuthenticatedUserDataWithDefaults() *UpdateAuthenticatedUserData {
	this := UpdateAuthenticatedUserData{}
	var password string = "unchanged"
	this.Password = &password
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UpdateAuthenticatedUserData) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAuthenticatedUserData) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UpdateAuthenticatedUserData) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UpdateAuthenticatedUserData) SetPassword(v string) {
	o.Password = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateAuthenticatedUserData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAuthenticatedUserData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateAuthenticatedUserData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateAuthenticatedUserData) SetVersion(v string) {
	o.Version = &v
}

func (o UpdateAuthenticatedUserData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateAuthenticatedUserData struct {
	value *UpdateAuthenticatedUserData
	isSet bool
}

func (v NullableUpdateAuthenticatedUserData) Get() *UpdateAuthenticatedUserData {
	return v.value
}

func (v *NullableUpdateAuthenticatedUserData) Set(val *UpdateAuthenticatedUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAuthenticatedUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAuthenticatedUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAuthenticatedUserData(val *UpdateAuthenticatedUserData) *NullableUpdateAuthenticatedUserData {
	return &NullableUpdateAuthenticatedUserData{value: val, isSet: true}
}

func (v NullableUpdateAuthenticatedUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAuthenticatedUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


