/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PoliciesSpecs struct for PoliciesSpecs
type PoliciesSpecs struct {
	// A unique identifier for a namespace. The format of this type is undefined and may change but the defined properties will not change.. 
	NamespaceID *string `json:"namespaceID,omitempty"`
	// The resource type this policy grants access to. 
	ResourceType *string `json:"resourceType,omitempty"`
	// If true, disallows requests that attempt to mutate the resource. 
	ReadOnly *bool `json:"readOnly,omitempty"`
}

// NewPoliciesSpecs instantiates a new PoliciesSpecs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoliciesSpecs() *PoliciesSpecs {
	this := PoliciesSpecs{}
	var readOnly bool = false
	this.ReadOnly = &readOnly
	return &this
}

// NewPoliciesSpecsWithDefaults instantiates a new PoliciesSpecs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoliciesSpecsWithDefaults() *PoliciesSpecs {
	this := PoliciesSpecs{}
	var readOnly bool = false
	this.ReadOnly = &readOnly
	return &this
}

// GetNamespaceID returns the NamespaceID field value if set, zero value otherwise.
func (o *PoliciesSpecs) GetNamespaceID() string {
	if o == nil || o.NamespaceID == nil {
		var ret string
		return ret
	}
	return *o.NamespaceID
}

// GetNamespaceIDOk returns a tuple with the NamespaceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoliciesSpecs) GetNamespaceIDOk() (*string, bool) {
	if o == nil || o.NamespaceID == nil {
		return nil, false
	}
	return o.NamespaceID, true
}

// HasNamespaceID returns a boolean if a field has been set.
func (o *PoliciesSpecs) HasNamespaceID() bool {
	if o != nil && o.NamespaceID != nil {
		return true
	}

	return false
}

// SetNamespaceID gets a reference to the given string and assigns it to the NamespaceID field.
func (o *PoliciesSpecs) SetNamespaceID(v string) {
	o.NamespaceID = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *PoliciesSpecs) GetResourceType() string {
	if o == nil || o.ResourceType == nil {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoliciesSpecs) GetResourceTypeOk() (*string, bool) {
	if o == nil || o.ResourceType == nil {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *PoliciesSpecs) HasResourceType() bool {
	if o != nil && o.ResourceType != nil {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *PoliciesSpecs) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *PoliciesSpecs) GetReadOnly() bool {
	if o == nil || o.ReadOnly == nil {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoliciesSpecs) GetReadOnlyOk() (*bool, bool) {
	if o == nil || o.ReadOnly == nil {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *PoliciesSpecs) HasReadOnly() bool {
	if o != nil && o.ReadOnly != nil {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *PoliciesSpecs) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

func (o PoliciesSpecs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NamespaceID != nil {
		toSerialize["namespaceID"] = o.NamespaceID
	}
	if o.ResourceType != nil {
		toSerialize["resourceType"] = o.ResourceType
	}
	if o.ReadOnly != nil {
		toSerialize["readOnly"] = o.ReadOnly
	}
	return json.Marshal(toSerialize)
}

type NullablePoliciesSpecs struct {
	value *PoliciesSpecs
	isSet bool
}

func (v NullablePoliciesSpecs) Get() *PoliciesSpecs {
	return v.value
}

func (v *NullablePoliciesSpecs) Set(val *PoliciesSpecs) {
	v.value = val
	v.isSet = true
}

func (v NullablePoliciesSpecs) IsSet() bool {
	return v.isSet
}

func (v *NullablePoliciesSpecs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoliciesSpecs(val *PoliciesSpecs) *NullablePoliciesSpecs {
	return &NullablePoliciesSpecs{value: val, isSet: true}
}

func (v NullablePoliciesSpecs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoliciesSpecs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


