/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// FsType The file system type of a volume. \"block\" is a raw block device (no filesystem). 
type FsType string

// List of FsType
const (
	FSTYPE_EXT2 FsType = "ext2"
	FSTYPE_EXT3 FsType = "ext3"
	FSTYPE_EXT4 FsType = "ext4"
	FSTYPE_XFS FsType = "xfs"
	FSTYPE_BTRFS FsType = "btrfs"
	FSTYPE_BLOCK FsType = "block"
)

// All allowed values of FsType enum
var AllowedFsTypeEnumValues = []FsType{
	"ext2",
	"ext3",
	"ext4",
	"xfs",
	"btrfs",
	"block",
}

func (v *FsType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FsType(value)
	for _, existing := range AllowedFsTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FsType", value)
}

// NewFsTypeFromValue returns a pointer to a valid FsType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFsTypeFromValue(v string) (*FsType, error) {
	ev := FsType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FsType: valid values are %v", v, AllowedFsTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FsType) IsValid() bool {
	for _, existing := range AllowedFsTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FsType value
func (v FsType) Ptr() *FsType {
	return &v
}

type NullableFsType struct {
	value *FsType
	isSet bool
}

func (v NullableFsType) Get() *FsType {
	return v.value
}

func (v *NullableFsType) Set(val *FsType) {
	v.value = val
	v.isSet = true
}

func (v NullableFsType) IsSet() bool {
	return v.isSet
}

func (v *NullableFsType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFsType(val *FsType) *NullableFsType {
	return &NullableFsType{value: val, isSet: true}
}

func (v NullableFsType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFsType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

