/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.5.0-beta1
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// CreatePolicyGroupData struct for CreatePolicyGroupData
type CreatePolicyGroupData struct {
	Name string `json:"name,omitempty"`
	// A set of authorisation policies to apply to the policy group.
	Specs *[]PoliciesSpecs `json:"specs,omitempty"`
}
