/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UserSessionAllOf struct for UserSessionAllOf
type UserSessionAllOf struct {
	Session *UserSessionAllOfSession `json:"session,omitempty"`
}

// NewUserSessionAllOf instantiates a new UserSessionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionAllOf() *UserSessionAllOf {
	this := UserSessionAllOf{}
	return &this
}

// NewUserSessionAllOfWithDefaults instantiates a new UserSessionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionAllOfWithDefaults() *UserSessionAllOf {
	this := UserSessionAllOf{}
	return &this
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *UserSessionAllOf) GetSession() UserSessionAllOfSession {
	if o == nil || o.Session == nil {
		var ret UserSessionAllOfSession
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSessionAllOf) GetSessionOk() (*UserSessionAllOfSession, bool) {
	if o == nil || o.Session == nil {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *UserSessionAllOf) HasSession() bool {
	if o != nil && o.Session != nil {
		return true
	}

	return false
}

// SetSession gets a reference to the given UserSessionAllOfSession and assigns it to the Session field.
func (o *UserSessionAllOf) SetSession(v UserSessionAllOfSession) {
	o.Session = &v
}

func (o UserSessionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Session != nil {
		toSerialize["session"] = o.Session
	}
	return json.Marshal(toSerialize)
}

type NullableUserSessionAllOf struct {
	value *UserSessionAllOf
	isSet bool
}

func (v NullableUserSessionAllOf) Get() *UserSessionAllOf {
	return v.value
}

func (v *NullableUserSessionAllOf) Set(val *UserSessionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionAllOf(val *UserSessionAllOf) *NullableUserSessionAllOf {
	return &NullableUserSessionAllOf{value: val, isSet: true}
}

func (v NullableUserSessionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


