/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// SetFailureModeRequest - struct for SetFailureModeRequest
type SetFailureModeRequest struct {
	SetFailureModeIntentRequestData *SetFailureModeIntentRequestData
	SetFailureThresholdRequestData *SetFailureThresholdRequestData
}

// SetFailureModeIntentRequestDataAsSetFailureModeRequest is a convenience function that returns SetFailureModeIntentRequestData wrapped in SetFailureModeRequest
func SetFailureModeIntentRequestDataAsSetFailureModeRequest(v *SetFailureModeIntentRequestData) SetFailureModeRequest {
	return SetFailureModeRequest{ SetFailureModeIntentRequestData: v}
}

// SetFailureThresholdRequestDataAsSetFailureModeRequest is a convenience function that returns SetFailureThresholdRequestData wrapped in SetFailureModeRequest
func SetFailureThresholdRequestDataAsSetFailureModeRequest(v *SetFailureThresholdRequestData) SetFailureModeRequest {
	return SetFailureModeRequest{ SetFailureThresholdRequestData: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SetFailureModeRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SetFailureModeIntentRequestData
	err = json.Unmarshal(data, &dst.SetFailureModeIntentRequestData)
	if err == nil {
		jsonSetFailureModeIntentRequestData, _ := json.Marshal(dst.SetFailureModeIntentRequestData)
		if string(jsonSetFailureModeIntentRequestData) == "{}" { // empty struct
			dst.SetFailureModeIntentRequestData = nil
		} else {
			match++
		}
	} else {
		dst.SetFailureModeIntentRequestData = nil
	}

	// try to unmarshal data into SetFailureThresholdRequestData
	err = json.Unmarshal(data, &dst.SetFailureThresholdRequestData)
	if err == nil {
		jsonSetFailureThresholdRequestData, _ := json.Marshal(dst.SetFailureThresholdRequestData)
		if string(jsonSetFailureThresholdRequestData) == "{}" { // empty struct
			dst.SetFailureThresholdRequestData = nil
		} else {
			match++
		}
	} else {
		dst.SetFailureThresholdRequestData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SetFailureModeIntentRequestData = nil
		dst.SetFailureThresholdRequestData = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(SetFailureModeRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(SetFailureModeRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SetFailureModeRequest) MarshalJSON() ([]byte, error) {
	if src.SetFailureModeIntentRequestData != nil {
		return json.Marshal(&src.SetFailureModeIntentRequestData)
	}

	if src.SetFailureThresholdRequestData != nil {
		return json.Marshal(&src.SetFailureThresholdRequestData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SetFailureModeRequest) GetActualInstance() (interface{}) {
	if obj.SetFailureModeIntentRequestData != nil {
		return obj.SetFailureModeIntentRequestData
	}

	if obj.SetFailureThresholdRequestData != nil {
		return obj.SetFailureThresholdRequestData
	}

	// all schemas are nil
	return nil
}

type NullableSetFailureModeRequest struct {
	value *SetFailureModeRequest
	isSet bool
}

func (v NullableSetFailureModeRequest) Get() *SetFailureModeRequest {
	return v.value
}

func (v *NullableSetFailureModeRequest) Set(val *SetFailureModeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetFailureModeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetFailureModeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetFailureModeRequest(val *SetFailureModeRequest) *NullableSetFailureModeRequest {
	return &NullableSetFailureModeRequest{value: val, isSet: true}
}

func (v NullableSetFailureModeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetFailureModeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


