/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// Cluster struct for Cluster
type Cluster struct {
	// A unique identifier for a cluster. The format of this type is undefined and may change but the defined properties will not change. 
	Id *string `json:"id,omitempty"`
	// Disables collection of telemetry data across the cluster.
	DisableTelemetry *bool `json:"disableTelemetry,omitempty"`
	// Disables collection of reports for any fatal crashes across the cluster. 
	DisableCrashReporting *bool `json:"disableCrashReporting,omitempty"`
	// Disables the mechanism responsible for checking if there is an updated version of StorageOS available for installation. 
	DisableVersionCheck *bool `json:"disableVersionCheck,omitempty"`
	LogLevel *LogLevel `json:"logLevel,omitempty"`
	LogFormat *LogFormat `json:"logFormat,omitempty"`
	// The time the entity was created. This timestamp is set by the node that created the entity, and may not be correct if the node's local clock was skewed. This value is for the user's informative purposes only, and correctness is not required. String format is RFC3339. 
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The time the entity was last updated. This timestamp is set by the node that last updated the entity, and may not be correct if the node's local clock was skewed. This value is for the user's informative purposes only, and correctness is not required. String format is RFC3339. 
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewCluster instantiates a new Cluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCluster() *Cluster {
	this := Cluster{}
	var disableTelemetry bool = false
	this.DisableTelemetry = &disableTelemetry
	var disableCrashReporting bool = false
	this.DisableCrashReporting = &disableCrashReporting
	var disableVersionCheck bool = false
	this.DisableVersionCheck = &disableVersionCheck
	var logLevel LogLevel = LOGLEVEL_INFO
	this.LogLevel = &logLevel
	var logFormat LogFormat = LOGFORMAT_DEFAULT
	this.LogFormat = &logFormat
	return &this
}

// NewClusterWithDefaults instantiates a new Cluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterWithDefaults() *Cluster {
	this := Cluster{}
	var disableTelemetry bool = false
	this.DisableTelemetry = &disableTelemetry
	var disableCrashReporting bool = false
	this.DisableCrashReporting = &disableCrashReporting
	var disableVersionCheck bool = false
	this.DisableVersionCheck = &disableVersionCheck
	var logLevel LogLevel = LOGLEVEL_INFO
	this.LogLevel = &logLevel
	var logFormat LogFormat = LOGFORMAT_DEFAULT
	this.LogFormat = &logFormat
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Cluster) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Cluster) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Cluster) SetId(v string) {
	o.Id = &v
}

// GetDisableTelemetry returns the DisableTelemetry field value if set, zero value otherwise.
func (o *Cluster) GetDisableTelemetry() bool {
	if o == nil || o.DisableTelemetry == nil {
		var ret bool
		return ret
	}
	return *o.DisableTelemetry
}

// GetDisableTelemetryOk returns a tuple with the DisableTelemetry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetDisableTelemetryOk() (*bool, bool) {
	if o == nil || o.DisableTelemetry == nil {
		return nil, false
	}
	return o.DisableTelemetry, true
}

// HasDisableTelemetry returns a boolean if a field has been set.
func (o *Cluster) HasDisableTelemetry() bool {
	if o != nil && o.DisableTelemetry != nil {
		return true
	}

	return false
}

// SetDisableTelemetry gets a reference to the given bool and assigns it to the DisableTelemetry field.
func (o *Cluster) SetDisableTelemetry(v bool) {
	o.DisableTelemetry = &v
}

// GetDisableCrashReporting returns the DisableCrashReporting field value if set, zero value otherwise.
func (o *Cluster) GetDisableCrashReporting() bool {
	if o == nil || o.DisableCrashReporting == nil {
		var ret bool
		return ret
	}
	return *o.DisableCrashReporting
}

// GetDisableCrashReportingOk returns a tuple with the DisableCrashReporting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetDisableCrashReportingOk() (*bool, bool) {
	if o == nil || o.DisableCrashReporting == nil {
		return nil, false
	}
	return o.DisableCrashReporting, true
}

// HasDisableCrashReporting returns a boolean if a field has been set.
func (o *Cluster) HasDisableCrashReporting() bool {
	if o != nil && o.DisableCrashReporting != nil {
		return true
	}

	return false
}

// SetDisableCrashReporting gets a reference to the given bool and assigns it to the DisableCrashReporting field.
func (o *Cluster) SetDisableCrashReporting(v bool) {
	o.DisableCrashReporting = &v
}

// GetDisableVersionCheck returns the DisableVersionCheck field value if set, zero value otherwise.
func (o *Cluster) GetDisableVersionCheck() bool {
	if o == nil || o.DisableVersionCheck == nil {
		var ret bool
		return ret
	}
	return *o.DisableVersionCheck
}

// GetDisableVersionCheckOk returns a tuple with the DisableVersionCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetDisableVersionCheckOk() (*bool, bool) {
	if o == nil || o.DisableVersionCheck == nil {
		return nil, false
	}
	return o.DisableVersionCheck, true
}

// HasDisableVersionCheck returns a boolean if a field has been set.
func (o *Cluster) HasDisableVersionCheck() bool {
	if o != nil && o.DisableVersionCheck != nil {
		return true
	}

	return false
}

// SetDisableVersionCheck gets a reference to the given bool and assigns it to the DisableVersionCheck field.
func (o *Cluster) SetDisableVersionCheck(v bool) {
	o.DisableVersionCheck = &v
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *Cluster) GetLogLevel() LogLevel {
	if o == nil || o.LogLevel == nil {
		var ret LogLevel
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetLogLevelOk() (*LogLevel, bool) {
	if o == nil || o.LogLevel == nil {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *Cluster) HasLogLevel() bool {
	if o != nil && o.LogLevel != nil {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given LogLevel and assigns it to the LogLevel field.
func (o *Cluster) SetLogLevel(v LogLevel) {
	o.LogLevel = &v
}

// GetLogFormat returns the LogFormat field value if set, zero value otherwise.
func (o *Cluster) GetLogFormat() LogFormat {
	if o == nil || o.LogFormat == nil {
		var ret LogFormat
		return ret
	}
	return *o.LogFormat
}

// GetLogFormatOk returns a tuple with the LogFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetLogFormatOk() (*LogFormat, bool) {
	if o == nil || o.LogFormat == nil {
		return nil, false
	}
	return o.LogFormat, true
}

// HasLogFormat returns a boolean if a field has been set.
func (o *Cluster) HasLogFormat() bool {
	if o != nil && o.LogFormat != nil {
		return true
	}

	return false
}

// SetLogFormat gets a reference to the given LogFormat and assigns it to the LogFormat field.
func (o *Cluster) SetLogFormat(v LogFormat) {
	o.LogFormat = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Cluster) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Cluster) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Cluster) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Cluster) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Cluster) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Cluster) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Cluster) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Cluster) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Cluster) SetVersion(v string) {
	o.Version = &v
}

func (o Cluster) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.DisableTelemetry != nil {
		toSerialize["disableTelemetry"] = o.DisableTelemetry
	}
	if o.DisableCrashReporting != nil {
		toSerialize["disableCrashReporting"] = o.DisableCrashReporting
	}
	if o.DisableVersionCheck != nil {
		toSerialize["disableVersionCheck"] = o.DisableVersionCheck
	}
	if o.LogLevel != nil {
		toSerialize["logLevel"] = o.LogLevel
	}
	if o.LogFormat != nil {
		toSerialize["logFormat"] = o.LogFormat
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableCluster struct {
	value *Cluster
	isSet bool
}

func (v NullableCluster) Get() *Cluster {
	return v.value
}

func (v *NullableCluster) Set(val *Cluster) {
	v.value = val
	v.isSet = true
}

func (v NullableCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCluster(val *Cluster) *NullableCluster {
	return &NullableCluster{value: val, isSet: true}
}

func (v NullableCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


