/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateVolumeData struct for CreateVolumeData
type CreateVolumeData struct {
	// A unique identifier for a namespace. The format of this type is undefined and may change but the defined properties will not change.. 
	NamespaceID string `json:"namespaceID"`
	// A set of arbitrary key value labels to apply to the entity. 
	Labels *map[string]string `json:"labels,omitempty"`
	// The name of the volume shown in the CLI and UI 
	Name string `json:"name"`
	FsType FsType `json:"fsType"`
	Description *string `json:"description,omitempty"`
	// A volume's size in bytes 
	SizeBytes uint64 `json:"sizeBytes"`
	PlacementStrategy *Strategy `json:"placementStrategy,omitempty"`
}

// NewCreateVolumeData instantiates a new CreateVolumeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVolumeData(namespaceID string, name string, fsType FsType, sizeBytes uint64) *CreateVolumeData {
	this := CreateVolumeData{}
	this.NamespaceID = namespaceID
	this.Name = name
	this.FsType = fsType
	this.SizeBytes = sizeBytes
	return &this
}

// NewCreateVolumeDataWithDefaults instantiates a new CreateVolumeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVolumeDataWithDefaults() *CreateVolumeData {
	this := CreateVolumeData{}
	return &this
}

// GetNamespaceID returns the NamespaceID field value
func (o *CreateVolumeData) GetNamespaceID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NamespaceID
}

// GetNamespaceIDOk returns a tuple with the NamespaceID field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetNamespaceIDOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NamespaceID, true
}

// SetNamespaceID sets field value
func (o *CreateVolumeData) SetNamespaceID(v string) {
	o.NamespaceID = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateVolumeData) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateVolumeData) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateVolumeData) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value
func (o *CreateVolumeData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateVolumeData) SetName(v string) {
	o.Name = v
}

// GetFsType returns the FsType field value
func (o *CreateVolumeData) GetFsType() FsType {
	if o == nil {
		var ret FsType
		return ret
	}

	return o.FsType
}

// GetFsTypeOk returns a tuple with the FsType field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetFsTypeOk() (*FsType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FsType, true
}

// SetFsType sets field value
func (o *CreateVolumeData) SetFsType(v FsType) {
	o.FsType = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateVolumeData) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateVolumeData) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateVolumeData) SetDescription(v string) {
	o.Description = &v
}

// GetSizeBytes returns the SizeBytes field value
func (o *CreateVolumeData) GetSizeBytes() uint64 {
	if o == nil {
		var ret uint64
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetSizeBytesOk() (*uint64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *CreateVolumeData) SetSizeBytes(v uint64) {
	o.SizeBytes = v
}

// GetPlacementStrategy returns the PlacementStrategy field value if set, zero value otherwise.
func (o *CreateVolumeData) GetPlacementStrategy() Strategy {
	if o == nil || o.PlacementStrategy == nil {
		var ret Strategy
		return ret
	}
	return *o.PlacementStrategy
}

// GetPlacementStrategyOk returns a tuple with the PlacementStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeData) GetPlacementStrategyOk() (*Strategy, bool) {
	if o == nil || o.PlacementStrategy == nil {
		return nil, false
	}
	return o.PlacementStrategy, true
}

// HasPlacementStrategy returns a boolean if a field has been set.
func (o *CreateVolumeData) HasPlacementStrategy() bool {
	if o != nil && o.PlacementStrategy != nil {
		return true
	}

	return false
}

// SetPlacementStrategy gets a reference to the given Strategy and assigns it to the PlacementStrategy field.
func (o *CreateVolumeData) SetPlacementStrategy(v Strategy) {
	o.PlacementStrategy = &v
}

func (o CreateVolumeData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["namespaceID"] = o.NamespaceID
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["fsType"] = o.FsType
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["sizeBytes"] = o.SizeBytes
	}
	if o.PlacementStrategy != nil {
		toSerialize["placementStrategy"] = o.PlacementStrategy
	}
	return json.Marshal(toSerialize)
}

type NullableCreateVolumeData struct {
	value *CreateVolumeData
	isSet bool
}

func (v NullableCreateVolumeData) Get() *CreateVolumeData {
	return v.value
}

func (v *NullableCreateVolumeData) Set(val *CreateVolumeData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVolumeData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVolumeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVolumeData(val *CreateVolumeData) *NullableCreateVolumeData {
	return &NullableCreateVolumeData{value: val, isSet: true}
}

func (v NullableCreateVolumeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVolumeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


