/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SetReplicasRequest struct for SetReplicasRequest
type SetReplicasRequest struct {
	// The number of replicas desired. 
	Replicas *uint64 `json:"replicas,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewSetReplicasRequest instantiates a new SetReplicasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetReplicasRequest() *SetReplicasRequest {
	this := SetReplicasRequest{}
	return &this
}

// NewSetReplicasRequestWithDefaults instantiates a new SetReplicasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetReplicasRequestWithDefaults() *SetReplicasRequest {
	this := SetReplicasRequest{}
	return &this
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *SetReplicasRequest) GetReplicas() uint64 {
	if o == nil || o.Replicas == nil {
		var ret uint64
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetReplicasRequest) GetReplicasOk() (*uint64, bool) {
	if o == nil || o.Replicas == nil {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *SetReplicasRequest) HasReplicas() bool {
	if o != nil && o.Replicas != nil {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given uint64 and assigns it to the Replicas field.
func (o *SetReplicasRequest) SetReplicas(v uint64) {
	o.Replicas = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SetReplicasRequest) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetReplicasRequest) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SetReplicasRequest) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SetReplicasRequest) SetVersion(v string) {
	o.Version = &v
}

func (o SetReplicasRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Replicas != nil {
		toSerialize["replicas"] = o.Replicas
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableSetReplicasRequest struct {
	value *SetReplicasRequest
	isSet bool
}

func (v NullableSetReplicasRequest) Get() *SetReplicasRequest {
	return v.value
}

func (v *NullableSetReplicasRequest) Set(val *SetReplicasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetReplicasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetReplicasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetReplicasRequest(val *SetReplicasRequest) *NullableSetReplicasRequest {
	return &NullableSetReplicasRequest{value: val, isSet: true}
}

func (v NullableSetReplicasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetReplicasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


