/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateClusterData struct for UpdateClusterData
type UpdateClusterData struct {
	// Disables collection of telemetry data across the cluster. 
	DisableTelemetry *bool `json:"disableTelemetry,omitempty"`
	// Disables collection of reports for any fatal crashes across the cluster. 
	DisableCrashReporting *bool `json:"disableCrashReporting,omitempty"`
	// Disables the mechanism responsible for checking if there is an updated version of StorageOS available for installation. 
	DisableVersionCheck *bool `json:"disableVersionCheck,omitempty"`
	LogLevel *LogLevel `json:"logLevel,omitempty"`
	LogFormat *LogFormat `json:"logFormat,omitempty"`
	// An opaque representation of an entity version at the time it was obtained from the API. All operations that mutate the entity must include this version field in the request unchanged. The format of this type is undefined and may change but the defined properties will not change. 
	Version *string `json:"version,omitempty"`
}

// NewUpdateClusterData instantiates a new UpdateClusterData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClusterData() *UpdateClusterData {
	this := UpdateClusterData{}
	var disableTelemetry bool = false
	this.DisableTelemetry = &disableTelemetry
	var disableCrashReporting bool = false
	this.DisableCrashReporting = &disableCrashReporting
	var disableVersionCheck bool = false
	this.DisableVersionCheck = &disableVersionCheck
	var logLevel LogLevel = LOGLEVEL_INFO
	this.LogLevel = &logLevel
	var logFormat LogFormat = LOGFORMAT_DEFAULT
	this.LogFormat = &logFormat
	return &this
}

// NewUpdateClusterDataWithDefaults instantiates a new UpdateClusterData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClusterDataWithDefaults() *UpdateClusterData {
	this := UpdateClusterData{}
	var disableTelemetry bool = false
	this.DisableTelemetry = &disableTelemetry
	var disableCrashReporting bool = false
	this.DisableCrashReporting = &disableCrashReporting
	var disableVersionCheck bool = false
	this.DisableVersionCheck = &disableVersionCheck
	var logLevel LogLevel = LOGLEVEL_INFO
	this.LogLevel = &logLevel
	var logFormat LogFormat = LOGFORMAT_DEFAULT
	this.LogFormat = &logFormat
	return &this
}

// GetDisableTelemetry returns the DisableTelemetry field value if set, zero value otherwise.
func (o *UpdateClusterData) GetDisableTelemetry() bool {
	if o == nil || o.DisableTelemetry == nil {
		var ret bool
		return ret
	}
	return *o.DisableTelemetry
}

// GetDisableTelemetryOk returns a tuple with the DisableTelemetry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetDisableTelemetryOk() (*bool, bool) {
	if o == nil || o.DisableTelemetry == nil {
		return nil, false
	}
	return o.DisableTelemetry, true
}

// HasDisableTelemetry returns a boolean if a field has been set.
func (o *UpdateClusterData) HasDisableTelemetry() bool {
	if o != nil && o.DisableTelemetry != nil {
		return true
	}

	return false
}

// SetDisableTelemetry gets a reference to the given bool and assigns it to the DisableTelemetry field.
func (o *UpdateClusterData) SetDisableTelemetry(v bool) {
	o.DisableTelemetry = &v
}

// GetDisableCrashReporting returns the DisableCrashReporting field value if set, zero value otherwise.
func (o *UpdateClusterData) GetDisableCrashReporting() bool {
	if o == nil || o.DisableCrashReporting == nil {
		var ret bool
		return ret
	}
	return *o.DisableCrashReporting
}

// GetDisableCrashReportingOk returns a tuple with the DisableCrashReporting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetDisableCrashReportingOk() (*bool, bool) {
	if o == nil || o.DisableCrashReporting == nil {
		return nil, false
	}
	return o.DisableCrashReporting, true
}

// HasDisableCrashReporting returns a boolean if a field has been set.
func (o *UpdateClusterData) HasDisableCrashReporting() bool {
	if o != nil && o.DisableCrashReporting != nil {
		return true
	}

	return false
}

// SetDisableCrashReporting gets a reference to the given bool and assigns it to the DisableCrashReporting field.
func (o *UpdateClusterData) SetDisableCrashReporting(v bool) {
	o.DisableCrashReporting = &v
}

// GetDisableVersionCheck returns the DisableVersionCheck field value if set, zero value otherwise.
func (o *UpdateClusterData) GetDisableVersionCheck() bool {
	if o == nil || o.DisableVersionCheck == nil {
		var ret bool
		return ret
	}
	return *o.DisableVersionCheck
}

// GetDisableVersionCheckOk returns a tuple with the DisableVersionCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetDisableVersionCheckOk() (*bool, bool) {
	if o == nil || o.DisableVersionCheck == nil {
		return nil, false
	}
	return o.DisableVersionCheck, true
}

// HasDisableVersionCheck returns a boolean if a field has been set.
func (o *UpdateClusterData) HasDisableVersionCheck() bool {
	if o != nil && o.DisableVersionCheck != nil {
		return true
	}

	return false
}

// SetDisableVersionCheck gets a reference to the given bool and assigns it to the DisableVersionCheck field.
func (o *UpdateClusterData) SetDisableVersionCheck(v bool) {
	o.DisableVersionCheck = &v
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *UpdateClusterData) GetLogLevel() LogLevel {
	if o == nil || o.LogLevel == nil {
		var ret LogLevel
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetLogLevelOk() (*LogLevel, bool) {
	if o == nil || o.LogLevel == nil {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *UpdateClusterData) HasLogLevel() bool {
	if o != nil && o.LogLevel != nil {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given LogLevel and assigns it to the LogLevel field.
func (o *UpdateClusterData) SetLogLevel(v LogLevel) {
	o.LogLevel = &v
}

// GetLogFormat returns the LogFormat field value if set, zero value otherwise.
func (o *UpdateClusterData) GetLogFormat() LogFormat {
	if o == nil || o.LogFormat == nil {
		var ret LogFormat
		return ret
	}
	return *o.LogFormat
}

// GetLogFormatOk returns a tuple with the LogFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetLogFormatOk() (*LogFormat, bool) {
	if o == nil || o.LogFormat == nil {
		return nil, false
	}
	return o.LogFormat, true
}

// HasLogFormat returns a boolean if a field has been set.
func (o *UpdateClusterData) HasLogFormat() bool {
	if o != nil && o.LogFormat != nil {
		return true
	}

	return false
}

// SetLogFormat gets a reference to the given LogFormat and assigns it to the LogFormat field.
func (o *UpdateClusterData) SetLogFormat(v LogFormat) {
	o.LogFormat = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateClusterData) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClusterData) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateClusterData) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateClusterData) SetVersion(v string) {
	o.Version = &v
}

func (o UpdateClusterData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DisableTelemetry != nil {
		toSerialize["disableTelemetry"] = o.DisableTelemetry
	}
	if o.DisableCrashReporting != nil {
		toSerialize["disableCrashReporting"] = o.DisableCrashReporting
	}
	if o.DisableVersionCheck != nil {
		toSerialize["disableVersionCheck"] = o.DisableVersionCheck
	}
	if o.LogLevel != nil {
		toSerialize["logLevel"] = o.LogLevel
	}
	if o.LogFormat != nil {
		toSerialize["logFormat"] = o.LogFormat
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateClusterData struct {
	value *UpdateClusterData
	isSet bool
}

func (v NullableUpdateClusterData) Get() *UpdateClusterData {
	return v.value
}

func (v *NullableUpdateClusterData) Set(val *UpdateClusterData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClusterData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClusterData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClusterData(val *UpdateClusterData) *NullableUpdateClusterData {
	return &NullableUpdateClusterData{value: val, isSet: true}
}

func (v NullableUpdateClusterData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClusterData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


