/*
StorageOS API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.0
Contact: info@storageos.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ReplicaDeploymentInfo struct for ReplicaDeploymentInfo
type ReplicaDeploymentInfo struct {
	// A unique identifier for a volume deployment. The format of this type is undefined and may change but the defined properties will not change. 
	Id *string `json:"id,omitempty"`
	// A unique identifier for a node. The format of this type is undefined and may change but the defined properties will not change. 
	NodeID *string `json:"nodeID,omitempty"`
	// The hostname of the node that is hosting the deployment 
	Hostname *string `json:"hostname,omitempty"`
	// Indicates if the volume deployment is eligible for promotion 
	Promotable *bool `json:"promotable,omitempty"`
	Health *ReplicaHealth `json:"health,omitempty"`
	SyncProgress *SyncProgress `json:"syncProgress,omitempty"`
}

// NewReplicaDeploymentInfo instantiates a new ReplicaDeploymentInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplicaDeploymentInfo() *ReplicaDeploymentInfo {
	this := ReplicaDeploymentInfo{}
	return &this
}

// NewReplicaDeploymentInfoWithDefaults instantiates a new ReplicaDeploymentInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplicaDeploymentInfoWithDefaults() *ReplicaDeploymentInfo {
	this := ReplicaDeploymentInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReplicaDeploymentInfo) SetId(v string) {
	o.Id = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetNodeID() string {
	if o == nil || o.NodeID == nil {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetNodeIDOk() (*string, bool) {
	if o == nil || o.NodeID == nil {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasNodeID() bool {
	if o != nil && o.NodeID != nil {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *ReplicaDeploymentInfo) SetNodeID(v string) {
	o.NodeID = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetHostname() string {
	if o == nil || o.Hostname == nil {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetHostnameOk() (*string, bool) {
	if o == nil || o.Hostname == nil {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasHostname() bool {
	if o != nil && o.Hostname != nil {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *ReplicaDeploymentInfo) SetHostname(v string) {
	o.Hostname = &v
}

// GetPromotable returns the Promotable field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetPromotable() bool {
	if o == nil || o.Promotable == nil {
		var ret bool
		return ret
	}
	return *o.Promotable
}

// GetPromotableOk returns a tuple with the Promotable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetPromotableOk() (*bool, bool) {
	if o == nil || o.Promotable == nil {
		return nil, false
	}
	return o.Promotable, true
}

// HasPromotable returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasPromotable() bool {
	if o != nil && o.Promotable != nil {
		return true
	}

	return false
}

// SetPromotable gets a reference to the given bool and assigns it to the Promotable field.
func (o *ReplicaDeploymentInfo) SetPromotable(v bool) {
	o.Promotable = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetHealth() ReplicaHealth {
	if o == nil || o.Health == nil {
		var ret ReplicaHealth
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetHealthOk() (*ReplicaHealth, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given ReplicaHealth and assigns it to the Health field.
func (o *ReplicaDeploymentInfo) SetHealth(v ReplicaHealth) {
	o.Health = &v
}

// GetSyncProgress returns the SyncProgress field value if set, zero value otherwise.
func (o *ReplicaDeploymentInfo) GetSyncProgress() SyncProgress {
	if o == nil || o.SyncProgress == nil {
		var ret SyncProgress
		return ret
	}
	return *o.SyncProgress
}

// GetSyncProgressOk returns a tuple with the SyncProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicaDeploymentInfo) GetSyncProgressOk() (*SyncProgress, bool) {
	if o == nil || o.SyncProgress == nil {
		return nil, false
	}
	return o.SyncProgress, true
}

// HasSyncProgress returns a boolean if a field has been set.
func (o *ReplicaDeploymentInfo) HasSyncProgress() bool {
	if o != nil && o.SyncProgress != nil {
		return true
	}

	return false
}

// SetSyncProgress gets a reference to the given SyncProgress and assigns it to the SyncProgress field.
func (o *ReplicaDeploymentInfo) SetSyncProgress(v SyncProgress) {
	o.SyncProgress = &v
}

func (o ReplicaDeploymentInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.NodeID != nil {
		toSerialize["nodeID"] = o.NodeID
	}
	if o.Hostname != nil {
		toSerialize["hostname"] = o.Hostname
	}
	if o.Promotable != nil {
		toSerialize["promotable"] = o.Promotable
	}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	if o.SyncProgress != nil {
		toSerialize["syncProgress"] = o.SyncProgress
	}
	return json.Marshal(toSerialize)
}

type NullableReplicaDeploymentInfo struct {
	value *ReplicaDeploymentInfo
	isSet bool
}

func (v NullableReplicaDeploymentInfo) Get() *ReplicaDeploymentInfo {
	return v.value
}

func (v *NullableReplicaDeploymentInfo) Set(val *ReplicaDeploymentInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableReplicaDeploymentInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableReplicaDeploymentInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplicaDeploymentInfo(val *ReplicaDeploymentInfo) *NullableReplicaDeploymentInfo {
	return &NullableReplicaDeploymentInfo{value: val, isSet: true}
}

func (v NullableReplicaDeploymentInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplicaDeploymentInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


