package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CreateVolumeOptions Parameters for creating new volumes.
// swagger:model CreateVolumeOptions
type CreateVolumeOptions struct {

	// Volume description.
	Description string `json:"Description,omitempty"`

	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels,omitempty"`

	// Volume name.
	// Required: true
	Name string `json:"Name"`

	// Name of capacity pool to provision the volume in, or the name of the current pool.
	Pool string `json:"Pool,omitempty"`

	// Size in GB.
	// Required: true
	Size int64 `json:"Size"`
}
