package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import strfmt "github.com/go-openapi/strfmt"

// Deployment Volume master or replica deployment details.
// swagger:model Deployment
type Deployment struct {

	// controller
	// Read Only: true
	Controller string `json:"Controller,omitempty"`

	// created at
	// Read Only: true
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// health
	// Read Only: true
	Health string `json:"Health,omitempty"`

	// ID
	// Read Only: true
	ID string `json:"ID,omitempty"`

	// inode
	// Read Only: true
	Inode uint32 `json:"Inode,omitempty"`

	// status
	// Read Only: true
	Status string `json:"Status,omitempty"`
}
