package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Volume A storage volume.
// swagger:model Volume
type Volume struct {

	// When the volume was created.
	// Read Only: true
	CreatedAt string `json:"CreatedAt,omitempty"`

	// User that created the volume.
	// Read Only: true
	CreatedBy string `json:"CreatedBy,omitempty"`

	// Flag indicating if the volume has been deleted and is waiting for scrubbing.
	// Read Only: true
	Deleted *bool `json:"Deleted,omitempty"`

	// Volume description.
	Description string `json:"Description,omitempty"`

	// Volume health, one of: healthy, degraded or dead.
	// Read Only: true
	Health string `json:"Health,omitempty"`

	// Volume unique ID.
	// Read Only: true
	ID string `json:"ID,omitempty"`

	// Block device inode.
	// Read Only: true
	Inode uint32 `json:"Inode,omitempty"`

	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels,omitempty"`

	// Volume deployment information for the master volume.
	// Read Only: true
	Master *Deployment `json:"Master,omitempty"`

	// Flag indicating if the volume is mounted and in use.
	// Read Only: true
	Mounted *bool `json:"Mounted,omitempty"`

	// When the volume was mounted.
	// Read Only: true
	MountedAt string `json:"MountedAt,omitempty"`

	// Reference to the node that has the volume mounted.
	// Read Only: true
	MountedBy string `json:"MountedBy,omitempty"`

	// Volume name.
	// Required: true
	Name string `json:"Name"`

	// Name of capacity pool to provision the volume in, or the name of the current pool.
	Pool string `json:"Pool,omitempty"`

	// Volume deployment information for the replica volumes.
	// Read Only: true
	Replicas []*Deployment `json:"Replicas"`

	// Size in GB.
	// Required: true
	Size int64 `json:"Size"`

	// Short status, one of: pending, evaluating, deploying, active, unavailable, failed, updating, deleting.
	// Read Only: true
	Status string `json:"Status,omitempty"`

	// Status message explaining current status.
	// Read Only: true
	StatusMessage string `json:"StatusMessage,omitempty"`
}
