/*
 * Ondat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.8.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// AcceptedMessage struct for AcceptedMessage
type AcceptedMessage struct {
	Msg string `json:"msg,omitempty"`
}
