/*
 * Ondat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.8.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
import (
	"time"
)
// Snapshot struct for Snapshot
type Snapshot struct {
	Name string `json:"name,omitempty"`
	Id string `json:"id,omitempty"`
	Location string `json:"location,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	SizeBytes float32 `json:"sizeBytes,omitempty"`
}
