/*
 * Ondat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.8.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// TopologyLabels List of requisite and preferred topology zones where the volume should be accessible from. 
type TopologyLabels struct {
	RequisiteZones []string `json:"requisiteZones,omitempty"`
	PreferredZones []string `json:"preferredZones,omitempty"`
}
