/*
 * Ondat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.8.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// MasterDeploymentInfoAllOf struct for MasterDeploymentInfoAllOf
type MasterDeploymentInfoAllOf struct {
	Health MasterHealth `json:"health,omitempty"`
}
